"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TablesWidget4 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var TablesWidget4 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: "card ".concat(className) },
        react_1.default.createElement("div", { className: 'card-header border-0 pt-5' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'card-label fw-bolder fs-3 mb-1' }, "New Members"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "More than 400 new members")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("ul", { className: 'nav' },
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary active fw-bolder px-4 me-1', "data-bs-toggle": 'tab', href: '#kt_table_widget_4_tab_1' }, "Month")),
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary fw-bolder px-4 me-1', "data-bs-toggle": 'tab', href: '#kt_table_widget_4_tab_2' }, "Week")),
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary fw-bolder px-4', "data-bs-toggle": 'tab', href: '#kt_table_widget_4_tab_3' }, "Day"))))),
        react_1.default.createElement("div", { className: 'card-body py-3' },
            react_1.default.createElement("div", { className: 'tab-content' },
                react_1.default.createElement("div", { className: 'tab-pane fade show active', id: 'kt_table_widget_4_tab_1' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-3' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-140px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-120px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-11.jpg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Brad Simmons"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Movie Creator")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-4.jpg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Jessie Clarcson"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "HTML, CSS Coding")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-5.jpg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Lebron Wayde"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "ReactJS Developer")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-6.jpg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Natali Trump"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "UI/UX Designer")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-9.jpg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Kevin Leonard"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Art Director")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' })))))))),
                react_1.default.createElement("div", { className: 'tab-pane fade', id: 'kt_table_widget_4_tab_2' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-3' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-140px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-120px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/043-boy-18.svg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Kevin Leonard"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Art Director")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/014-girl-7.svg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Natali Trump"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "UI/UX Designer")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/018-girl-9.svg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Jessie Clarcson"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "HTML, CSS Coding")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/001-boy.svg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Brad Simmons"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Movie Creator")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' })))))))),
                react_1.default.createElement("div", { className: 'tab-pane fade', id: 'kt_table_widget_4_tab_3' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-3' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-140px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-120px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/018-girl-9.svg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Jessie Clarcson"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "HTML, CSS Coding")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/047-girl-25.svg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Lebron Wayde"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "ReactJS Developer")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/014-girl-7.svg'), alt: '' }))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Natali Trump"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "UI/UX Designer")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Rating"),
                                        react_1.default.createElement("div", { className: 'rating' },
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                            react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                                react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })))),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-twitter btn-sm me-3' },
                                            react_1.default.createElement("i", { className: 'bi bi-twitter fs-4' })),
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light-facebook btn-sm' },
                                            react_1.default.createElement("i", { className: 'bi bi-facebook fs-4' }))))))))))));
};
exports.TablesWidget4 = TablesWidget4;
