"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TablesWidget11 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var TablesWidget11 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: "card ".concat(className) },
        react_1.default.createElement("div", { className: 'card-header border-0 pt-5' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'card-label fw-bolder fs-3 mb-1' }, "New Arrivals"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "Over 500 new products")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-light-primary' },
                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr075.svg', className: 'svg-icon-2' }),
                    "New Member"))),
        react_1.default.createElement("div", { className: 'card-body py-3' },
            react_1.default.createElement("div", { className: 'table-responsive' },
                react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-4' },
                    react_1.default.createElement("thead", null,
                        react_1.default.createElement("tr", { className: 'fw-bolder text-muted bg-light' },
                            react_1.default.createElement("th", { className: 'ps-4 min-w-325px rounded-start' }, "Product"),
                            react_1.default.createElement("th", { className: 'min-w-125px' }, "Price"),
                            react_1.default.createElement("th", { className: 'min-w-125px' }, "Deposit"),
                            react_1.default.createElement("th", { className: 'min-w-200px' }, "Agent"),
                            react_1.default.createElement("th", { className: 'min-w-150px' }, "Status"),
                            react_1.default.createElement("th", { className: 'min-w-200px text-end rounded-end' }))),
                    react_1.default.createElement("tbody", null,
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/stock/600x400/img-26.jpg'), className: '', alt: '' })),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Sant Extreanet Solution"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "HTML, JS, ReactJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$2,790"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$520"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Rejected")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Bradly Beal"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Insurance")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("span", { className: 'badge badge-light-primary fs-7 fw-bold' }, "Approved")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/stock/600x400/img-3.jpg'), className: '', alt: '' })),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Telegram Development"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "C#, ASP.NET, MS SQL")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$4,790"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$240"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Rejected")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Chris Thompson"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "NBA Player")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("span", { className: 'badge badge-light-danger fs-7 fw-bold' }, "In Progress")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/stock/600x400/img-9.jpg'), className: '', alt: '' })),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Payroll Application"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "PHP, Laravel, VueJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$4,390"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$593"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Rejected")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Zoey McGee"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Ruby Developer")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("span", { className: 'badge badge-light-success fs-7 fw-bold' }, "Success")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/stock/600x400/img-18.jpg'), className: '', alt: '' })),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "HR Management System"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Python, PostgreSQL, ReactJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$7,990"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$980"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Rejected")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Brandon Ingram"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Insurance")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("span", { className: 'badge badge-light-info fs-7 fw-bold' }, "Rejected")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/stock/600x400/img-8.jpg'), className: '', alt: '' })),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Telegram Mobile"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "HTML, JS, ReactJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$5,790"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$750"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Rejected")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Natali Trump"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Insurance")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("span", { className: 'badge badge-light-warning fs-7 fw-bold' }, "Approved")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' }))))))))));
};
exports.TablesWidget11 = TablesWidget11;
