"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TablesWidget10 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var TablesWidget10 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: "card ".concat(className) },
        react_1.default.createElement("div", { className: 'card-header border-0 pt-5' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'card-label fw-bolder fs-3 mb-1' }, "Members Statistics"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "Over 500 members")),
            react_1.default.createElement("div", { className: 'card-toolbar', "data-bs-toggle": 'tooltip', "data-bs-placement": 'top', "data-bs-trigger": 'hover', title: 'Click to add a user' },
                react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-light-primary' },
                    react_1.default.createElement(helpers_1.KTSVG, { path: 'media/icons/duotune/arrows/arr075.svg', className: 'svg-icon-3' }),
                    "New Member"))),
        react_1.default.createElement("div", { className: 'card-body py-3' },
            react_1.default.createElement("div", { className: 'table-responsive' },
                react_1.default.createElement("table", { className: 'table table-row-dashed table-row-gray-300 align-middle gs-0 gy-4' },
                    react_1.default.createElement("thead", null,
                        react_1.default.createElement("tr", { className: 'fw-bolder text-muted' },
                            react_1.default.createElement("th", { className: 'w-25px' },
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input', type: 'checkbox', value: '1', "data-kt-check": 'true', "data-kt-check-target": '.widget-9-check' }))),
                            react_1.default.createElement("th", { className: 'min-w-150px' }, "Authors"),
                            react_1.default.createElement("th", { className: 'min-w-140px' }, "Company"),
                            react_1.default.createElement("th", { className: 'min-w-120px' }, "Progress"),
                            react_1.default.createElement("th", { className: 'min-w-100px text-end' }, "Actions"))),
                    react_1.default.createElement("tbody", null,
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input widget-9-check', type: 'checkbox', value: '1' }))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-45px me-5' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-11.jpg'), alt: '' })),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary fs-6' }, "Ana Simmons"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "HTML, JS, ReactJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block fs-6' }, "Intertico"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Web, UI/UX Design")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("div", { className: 'd-flex flex-column w-100 me-2' },
                                    react_1.default.createElement("div", { className: 'd-flex flex-stack mb-2' },
                                        react_1.default.createElement("span", { className: 'text-muted me-2 fs-7 fw-bold' }, "50%")),
                                    react_1.default.createElement("div", { className: 'progress h-6px w-100' },
                                        react_1.default.createElement("div", { className: 'progress-bar bg-primary', role: 'progressbar', style: { width: '50%' } })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex justify-content-end flex-shrink-0' },
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' }))))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input widget-9-check', type: 'checkbox', value: '1' }))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-45px me-5' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-3.jpg'), alt: '' })),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary fs-6' }, "Jessie Clarcson"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "C#, ASP.NET, MS SQL")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block fs-6' }, "Agoda"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Houses & Hotels")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("div", { className: 'd-flex flex-column w-100 me-2' },
                                    react_1.default.createElement("div", { className: 'd-flex flex-stack mb-2' },
                                        react_1.default.createElement("span", { className: 'text-muted me-2 fs-7 fw-bold' }, "70%")),
                                    react_1.default.createElement("div", { className: 'progress h-6px w-100' },
                                        react_1.default.createElement("div", { className: 'progress-bar bg-danger', role: 'progressbar', style: { width: '70%' } })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex justify-content-end flex-shrink-0' },
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' }))))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input widget-9-check', type: 'checkbox', value: '1' }))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-45px me-5' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-4.jpg'), alt: '' })),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary fs-6' }, "Lebron Wayde"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "PHP, Laravel, VueJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block fs-6' }, "RoadGee"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Transportation")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("div", { className: 'd-flex flex-column w-100 me-2' },
                                    react_1.default.createElement("div", { className: 'd-flex flex-stack mb-2' },
                                        react_1.default.createElement("span", { className: 'text-muted me-2 fs-7 fw-bold' }, "60%")),
                                    react_1.default.createElement("div", { className: 'progress h-6px w-100' },
                                        react_1.default.createElement("div", { className: 'progress-bar bg-success', role: 'progressbar', style: { width: '60%' } })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex justify-content-end flex-shrink-0' },
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' }))))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input widget-9-check', type: 'checkbox', value: '1' }))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-45px me-5' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-5.jpg'), alt: '' })),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary fs-6' }, "Natali Goodwin"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Python, PostgreSQL, ReactJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block fs-6' }, "The Hill"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Insurance")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("div", { className: 'd-flex flex-column w-100 me-2' },
                                    react_1.default.createElement("div", { className: 'd-flex flex-stack mb-2' },
                                        react_1.default.createElement("span", { className: 'text-muted me-2 fs-7 fw-bold' }, "50%")),
                                    react_1.default.createElement("div", { className: 'progress h-6px w-100' },
                                        react_1.default.createElement("div", { className: 'progress-bar bg-warning', role: 'progressbar', style: { width: '50%' } })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex justify-content-end flex-shrink-0' },
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' }))))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input widget-9-check', type: 'checkbox', value: '1' }))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-45px me-5' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-6.jpg'), alt: '' })),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary fs-6' }, "Kevin Leonard"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "HTML, JS, ReactJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block fs-6' }, "RoadGee"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Art Director")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("div", { className: 'd-flex flex-column w-100 me-2' },
                                    react_1.default.createElement("div", { className: 'd-flex flex-stack mb-2' },
                                        react_1.default.createElement("span", { className: 'text-muted me-2 fs-7 fw-bold' }, "90%")),
                                    react_1.default.createElement("div", { className: 'progress h-6px w-100' },
                                        react_1.default.createElement("div", { className: 'progress-bar bg-info', role: 'progressbar', style: { width: '90%' } })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex justify-content-end flex-shrink-0' },
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                    react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' })))))))))));
};
exports.TablesWidget10 = TablesWidget10;
