"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TablesWidget8 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var TablesWidget8 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: "card ".concat(className) },
        react_1.default.createElement("div", { className: 'card-header border-0 pt-5' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'card-label fw-bolder fs-3 mb-1' }, "Latest Products"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "More than 100 new orders")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("ul", { className: 'nav' },
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary active fw-bolder px-4 me-1', "data-bs-toggle": 'tab', href: '#kt_table_widget_8_tab_1' }, "Month")),
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary fw-bolder px-4 me-1', "data-bs-toggle": 'tab', href: '#kt_table_widget_8_tab_2' }, "Week")),
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary fw-bolder px-4', "data-bs-toggle": 'tab', href: '#kt_table_widget_8_tab_3' }, "Day"))))),
        react_1.default.createElement("div", { className: 'card-body py-3' },
            react_1.default.createElement("div", { className: 'tab-content' },
                react_1.default.createElement("div", { className: 'tab-pane fade show active', id: 'kt_table_widget_8_tab_1' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-3' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-120px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-danger' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/coding/cod002.svg', className: 'svg-icon-2x svg-icon-danger' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "School Music Festival"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "by Rose Liam")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "4:20PM, 03 Sep"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-warning' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen024.svg', className: 'svg-icon-2x svg-icon-warning' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Maths Championship"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "By Tom Gere")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "10:05PM, 25 Oct"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-info' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/maps/map004.svg', className: 'svg-icon-2x svg-icon-info' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Who Knows Geography"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "By Zoey Dylan")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "3:22PM, 07 Sep"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-primary' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/abstract/abs027.svg', className: 'svg-icon-2x svg-icon-primary' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Napoleon Days"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "By Luke Owen")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "1:20PM, 02 Dec"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-success' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art007.svg', className: 'svg-icon-2x svg-icon-success' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "The School Art Leads"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "By Ellie Cole")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "6:20PM, 07 Sep"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' })))))))),
                react_1.default.createElement("div", { className: 'tab-pane fade', id: 'kt_table_widget_8_tab_2' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-3' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-120px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-info' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/maps/map004.svg', className: 'svg-icon-2x svg-icon-info' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Who Knows Geography"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "By Zoey Dylan")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "3:22PM, 07 Sep"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-warning' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen024.svg', className: 'svg-icon-2x svg-icon-warning' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Maths Championship"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "By Tom Gere")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "10:05PM, 25 Oct"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-danger' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/coding/cod002.svg', className: 'svg-icon-2x svg-icon-danger' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "School Music Festival"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "by Rose Liam")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "4:20PM, 03 Sep"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' })))))))),
                react_1.default.createElement("div", { className: 'tab-pane fade', id: 'kt_table_widget_8_tab_3' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-3' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-120px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-warning' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen024.svg', className: 'svg-icon-2x svg-icon-warning' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Maths Championship"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "By Tom Gere")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "10:05PM, 25 Oct"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-info' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/maps/map004.svg', className: 'svg-icon-2x svg-icon-info' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Who Knows Geography"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "By Zoey Dylan")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "3:22PM, 07 Sep"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-primary' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/abstract/abs027.svg', className: 'svg-icon-2x svg-icon-primary' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Napoleon Days"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "By Luke Owen")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "1:20PM, 02 Dec"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label bg-light-danger' },
                                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/coding/cod002.svg', className: 'svg-icon-2x svg-icon-danger' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "School Music Festival"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "by Rose Liam")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-7' }, "4:20PM, 03 Sep"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-8' }, "Date")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement("i", { className: 'bi bi-three-dots fs-5' }))))))))))));
};
exports.TablesWidget8 = TablesWidget8;
