"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TablesWidget12 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var TablesWidget12 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: "card ".concat(className) },
        react_1.default.createElement("div", { className: 'card-header border-0 pt-5' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'card-label fw-bolder fs-3 mb-1' }, "Member Statistics"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "Over 500 new members")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("button", { type: 'button', className: 'btn btn-sm btn-icon btn-color-primary btn-active-light-primary', "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'bottom-end', "data-kt-menu-flip": 'top-end' },
                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen024.svg', className: 'svg-icon-2' })),
                react_1.default.createElement("div", { className: 'menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold w-200px', "data-kt-menu": 'true' },
                    react_1.default.createElement("div", { className: 'menu-item px-3' },
                        react_1.default.createElement("div", { className: 'menu-content fs-6 text-dark fw-bolder px-3 py-4' }, "Quick Actions")),
                    react_1.default.createElement("div", { className: 'separator mb-3 opacity-75' }),
                    react_1.default.createElement("div", { className: 'menu-item px-3' },
                        react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "New Ticket")),
                    react_1.default.createElement("div", { className: 'menu-item px-3' },
                        react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "New Customer")),
                    react_1.default.createElement("div", { className: 'menu-item px-3', "data-kt-menu-trigger": 'hover', "data-kt-menu-placement": 'right-start', "data-kt-menu-flip": 'left-start, top' },
                        react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' },
                            react_1.default.createElement("span", { className: 'menu-title' }, "New Group"),
                            react_1.default.createElement("span", { className: 'menu-arrow' })),
                        react_1.default.createElement("div", { className: 'menu-sub menu-sub-dropdown w-175px py-4' },
                            react_1.default.createElement("div", { className: 'menu-item px-3' },
                                react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "Admin Group")),
                            react_1.default.createElement("div", { className: 'menu-item px-3' },
                                react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "Staff Group")),
                            react_1.default.createElement("div", { className: 'menu-item px-3' },
                                react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "Member Group")))),
                    react_1.default.createElement("div", { className: 'menu-item px-3' },
                        react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "New Contact")),
                    react_1.default.createElement("div", { className: 'separator mt-3 opacity-75' }),
                    react_1.default.createElement("div", { className: 'menu-item px-3' },
                        react_1.default.createElement("div", { className: 'menu-content px-3 py-3' },
                            react_1.default.createElement("a", { className: 'btn btn-primary btn-sm px-4', href: '#' }, "Generate Reports")))))),
        react_1.default.createElement("div", { className: 'card-body py-3' },
            react_1.default.createElement("div", { className: 'table-responsive' },
                react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-4' },
                    react_1.default.createElement("thead", null,
                        react_1.default.createElement("tr", { className: 'fw-bolder text-muted bg-light' },
                            react_1.default.createElement("th", { className: 'ps-4 min-w-300px rounded-start' }, "Agent"),
                            react_1.default.createElement("th", { className: 'min-w-125px' }, "Earnings"),
                            react_1.default.createElement("th", { className: 'min-w-125px' }, "Comission"),
                            react_1.default.createElement("th", { className: 'min-w-200px' }, "Company"),
                            react_1.default.createElement("th", { className: 'min-w-150px' }, "Rating"),
                            react_1.default.createElement("th", { className: 'min-w-200px text-end rounded-end' }))),
                    react_1.default.createElement("tbody", null,
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                                        react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/001-boy.svg'), className: 'h-75 align-self-end', alt: '' }))),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Brad Simmons"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "HTML, JS, ReactJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$8,000,000"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Pending")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$5,400"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Intertico"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Web, UI/UX Design")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'rating' },
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' }))),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7 mt-1' }, "Best Rated")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4 me-2' }, "View"),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4' }, "Edit"))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                                        react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/047-girl-25.svg'), className: 'h-75 align-self-end', alt: '' }))),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Lebron Wayde"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "PHP, Laravel, VueJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$8,750,000"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$7,400"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Agoda"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Houses & Hotels")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'rating' },
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' }))),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7 mt-1' }, "Above Avarage")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4 me-2' }, "View"),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4' }, "Edit"))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                                        react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/006-girl-3.svg'), className: 'h-75 align-self-end', alt: '' }))),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Brad Simmons"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "HTML, JS, ReactJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$8,000,000"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "In Proccess")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$2,500"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Rejected")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "RoadGee"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'rating' },
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' }))),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7 mt-1' }, "Best Rated")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4 me-2' }, "View"),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4' }, "Edit"))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                                        react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/014-girl-7.svg'), className: 'h-75 align-self-end', alt: '' }))),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Natali Trump"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "HTML, JS, ReactJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$700,000"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Pending")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$7,760"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "The Hill"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Insurance")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'rating' },
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' }))),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7 mt-1' }, "Avarage")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4 me-2' }, "View"),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4' }, "Edit"))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                                    react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                                        react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                            react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/020-girl-11.svg'), className: 'h-75 align-self-end', alt: '' }))),
                                    react_1.default.createElement("div", { className: 'd-flex justify-content-start flex-column' },
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Jessie Clarcson"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "HTML, JS, ReactJS")))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$1,320,000"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Pending")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "$6,250"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Intertico"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Web, UI/UX Design")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'rating' },
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' })),
                                    react_1.default.createElement("div", { className: 'rating-label me-2 checked' },
                                        react_1.default.createElement("i", { className: 'bi bi-star-fill fs-5' }))),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7 mt-1' }, "Best Rated")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4 me-2' }, "View"),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4' }, "Edit")))))))));
};
exports.TablesWidget12 = TablesWidget12;
