"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TablesWidget5 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var TablesWidget5 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: "card ".concat(className) },
        react_1.default.createElement("div", { className: 'card-header border-0 pt-5' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'card-label fw-bolder fs-3 mb-1' }, "Latest Products"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "More than 400 new products")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("ul", { className: 'nav' },
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary active fw-bolder px-4 me-1', "data-bs-toggle": 'tab', href: '#kt_table_widget_5_tab_1' }, "Month")),
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary fw-bolder px-4 me-1', "data-bs-toggle": 'tab', href: '#kt_table_widget_5_tab_2' }, "Week")),
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary fw-bolder px-4', "data-bs-toggle": 'tab', href: '#kt_table_widget_5_tab_3' }, "Day"))))),
        react_1.default.createElement("div", { className: 'card-body py-3' },
            react_1.default.createElement("div", { className: 'tab-content' },
                react_1.default.createElement("div", { className: 'tab-pane fade show active', id: 'kt_table_widget_5_tab_1' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table table-row-dashed table-row-gray-200 align-middle gs-0 gy-4' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", { className: 'border-0' },
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-140px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-110px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-50px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/plurk.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Brad Simmons"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Movie Creator")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "React, HTML"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-success' }, "Approved")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/telegram.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Popular Authors"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Most Successful")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "Python, MySQL"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-warning' }, "In Progress")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/vimeo.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "New Users"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Awesome Users")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "Laravel,Metronic"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-primary' }, "Success")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/bebo.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Active Customers"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Movie Creator")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "AngularJS, C#"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-danger' }, "Rejected")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/kickstarter.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Bestseller Theme"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Best Customers")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "ReactJS, Ruby"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-warning' }, "In Progress")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))))))),
                react_1.default.createElement("div", { className: 'tab-pane fade', id: 'kt_table_widget_5_tab_2' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table table-row-dashed table-row-gray-200 align-middle gs-0 gy-4' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", { className: 'border-0' },
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-140px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-110px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-50px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/plurk.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Brad Simmons"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Movie Creator")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "React, HTML"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-success' }, "Approved")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/telegram.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Popular Authors"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Most Successful")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "Python, MySQL"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-warning' }, "In Progress")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/bebo.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Active Customers"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Movie Creator")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "AngularJS, C#"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-danger' }, "Rejected")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))))))),
                react_1.default.createElement("div", { className: 'tab-pane fade', id: 'kt_table_widget_5_tab_3' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table table-row-dashed table-row-gray-200 align-middle gs-0 gy-4' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", { className: 'border-0' },
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-140px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-110px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-50px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/kickstarter.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Bestseller Theme"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Best Customers")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "ReactJS, Ruby"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-warning' }, "In Progress")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/bebo.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Active Customers"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Movie Creator")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "AngularJS, C#"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-danger' }, "Rejected")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/vimeo.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "New Users"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Awesome Users")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "Laravel,Metronic"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-primary' }, "Success")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-45px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/telegram.svg'), className: 'h-50 align-self-center', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Popular Authors"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Most Successful")),
                                    react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "Python, MySQL"),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'badge badge-light-warning' }, "In Progress")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' }))))))))))));
};
exports.TablesWidget5 = TablesWidget5;
