"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TablesWidget2 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var helpers_2 = require("../../../helpers");
var Dropdown1_1 = require("../../content/dropdown/Dropdown1");
var TablesWidget2 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: "card ".concat(className) },
        react_1.default.createElement("div", { className: 'card-header border-0 pt-5' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'card-label fw-bolder fs-3 mb-1' }, "Latest Arrivals"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "More than 100 new products")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("button", { type: 'button', className: 'btn btn-sm btn-icon btn-color-primary btn-active-light-primary', "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'bottom-end', "data-kt-menu-flip": 'top-end' },
                    react_1.default.createElement(helpers_2.KTSVG, { path: 'media/icons/duotune/general/gen024.svg', className: 'svg-icon-2' })),
                react_1.default.createElement(Dropdown1_1.Dropdown1, null))),
        react_1.default.createElement("div", { className: 'card-body py-3' },
            react_1.default.createElement("div", { className: 'table-responsive' },
                react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-5' },
                    react_1.default.createElement("thead", null,
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                            react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                            react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                            react_1.default.createElement("th", { className: 'p-0 min-w-125px' }),
                            react_1.default.createElement("th", { className: 'p-0 min-w-40px' }))),
                    react_1.default.createElement("tbody", null,
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                    react_1.default.createElement("span", { className: 'symbol-label' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/plurk.svg'), className: 'h-50 align-self-center', alt: '' })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Top Authors"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Successful Fellas")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("span", { className: 'badge badge-light-danger fw-bold me-1' }, "Angular"),
                                react_1.default.createElement("span", { className: 'badge badge-light-info fw-bold me-1' }, "PHP")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("span", { className: 'text-muted fw-bold' }, "4600 Users")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                    react_1.default.createElement(helpers_2.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                    react_1.default.createElement("span", { className: 'symbol-label' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/telegram.svg'), className: 'h-50 align-self-center', alt: '' })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Popular Authors"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Most Successful")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("span", { className: 'badge badge-light-danger fw-bold me-1' }, "HTML"),
                                react_1.default.createElement("span", { className: 'badge badge-light-info fw-bold me-1' }, "CSS")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("span", { className: 'text-muted fw-bold' }, "7200 Users")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                    react_1.default.createElement(helpers_2.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                    react_1.default.createElement("span", { className: 'symbol-label' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/vimeo.svg'), className: 'h-50 align-self-center', alt: '' })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "New Users"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Awesome Users")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("span", { className: 'badge badge-light-danger fw-bold me-1' }, "React"),
                                react_1.default.createElement("span", { className: 'badge badge-light-info fw-bold me-1' }, "SASS")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("span", { className: 'text-muted fw-bold' }, "890 Users")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                    react_1.default.createElement(helpers_2.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                    react_1.default.createElement("span", { className: 'symbol-label' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/bebo.svg'), className: 'h-50 align-self-center', alt: '' })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Active Customers"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Best Customers")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("span", { className: 'badge badge-light-danger fw-bold me-1' }, "Java"),
                                react_1.default.createElement("span", { className: 'badge badge-light-info fw-bold me-1' }, "PHP")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("span", { className: 'text-muted fw-bold' }, "6370 Users")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                    react_1.default.createElement(helpers_2.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                    react_1.default.createElement("span", { className: 'symbol-label' },
                                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/kickstarter.svg'), className: 'h-50 align-self-center', alt: '' })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Bestseller Theme"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Amazing Templates")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("span", { className: 'badge badge-light-danger fw-bold me-1' }, "Python"),
                                react_1.default.createElement("span", { className: 'badge badge-light-info fw-bold me-1' }, "MySQL")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("span", { className: 'text-muted fw-bold' }, "354 Users")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                    react_1.default.createElement(helpers_2.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' }))))))))));
};
exports.TablesWidget2 = TablesWidget2;
