"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TablesWidget13 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var TablesWidget13 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: "card ".concat(className) },
        react_1.default.createElement("div", { className: 'card-header border-0 pt-5' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'card-label fw-bolder fs-3 mb-1' }, "Recent Orders"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "Over 500 orders")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("button", { type: 'button', className: 'btn btn-sm btn-icon btn-color-primary btn-active-light-primary', "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'bottom-end', "data-kt-menu-flip": 'top-end' },
                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen024.svg', className: 'svg-icon-2' })),
                react_1.default.createElement("div", { className: 'menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold w-200px', "data-kt-menu": 'true' },
                    react_1.default.createElement("div", { className: 'menu-item px-3' },
                        react_1.default.createElement("div", { className: 'menu-content fs-6 text-dark fw-bolder px-3 py-4' }, "Quick Actions")),
                    react_1.default.createElement("div", { className: 'separator mb-3 opacity-75' }),
                    react_1.default.createElement("div", { className: 'menu-item px-3' },
                        react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "New Ticket")),
                    react_1.default.createElement("div", { className: 'menu-item px-3' },
                        react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "New Customer")),
                    react_1.default.createElement("div", { className: 'menu-item px-3', "data-kt-menu-trigger": 'hover', "data-kt-menu-placement": 'right-start', "data-kt-menu-flip": 'left-start, top' },
                        react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' },
                            react_1.default.createElement("span", { className: 'menu-title' }, "New Group"),
                            react_1.default.createElement("span", { className: 'menu-arrow' })),
                        react_1.default.createElement("div", { className: 'menu-sub menu-sub-dropdown w-175px py-4' },
                            react_1.default.createElement("div", { className: 'menu-item px-3' },
                                react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "Admin Group")),
                            react_1.default.createElement("div", { className: 'menu-item px-3' },
                                react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "Staff Group")),
                            react_1.default.createElement("div", { className: 'menu-item px-3' },
                                react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "Member Group")))),
                    react_1.default.createElement("div", { className: 'menu-item px-3' },
                        react_1.default.createElement("a", { href: '#', className: 'menu-link px-3' }, "New Contact")),
                    react_1.default.createElement("div", { className: 'separator mt-3 opacity-75' }),
                    react_1.default.createElement("div", { className: 'menu-item px-3' },
                        react_1.default.createElement("div", { className: 'menu-content px-3 py-3' },
                            react_1.default.createElement("a", { className: 'btn btn-primary btn-sm px-4', href: '#' }, "Generate Reports")))))),
        react_1.default.createElement("div", { className: 'card-body py-3' },
            react_1.default.createElement("div", { className: 'table-responsive' },
                react_1.default.createElement("table", { className: 'table table-row-bordered table-row-gray-100 align-middle gs-0 gy-3' },
                    react_1.default.createElement("thead", null,
                        react_1.default.createElement("tr", { className: 'fw-bolder text-muted' },
                            react_1.default.createElement("th", { className: 'w-25px' },
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input', type: 'checkbox', value: '1', "data-kt-check": 'true', "data-kt-check-target": '.widget-13-check' }))),
                            react_1.default.createElement("th", { className: 'min-w-150px' }, "Order Id"),
                            react_1.default.createElement("th", { className: 'min-w-140px' }, "Country"),
                            react_1.default.createElement("th", { className: 'min-w-120px' }, "Date"),
                            react_1.default.createElement("th", { className: 'min-w-120px' }, "Company"),
                            react_1.default.createElement("th", { className: 'min-w-120px' }, "Total"),
                            react_1.default.createElement("th", { className: 'min-w-120px' }, "Status"),
                            react_1.default.createElement("th", { className: 'min-w-100px text-end' }, "Actions"))),
                    react_1.default.createElement("tbody", null,
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input widget-13-check', type: 'checkbox', value: '1' }))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary fs-6' }, "56037-XDER")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Brasil"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Code: PH")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "05/28/2020"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Code: Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Intertico"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Web, UI/UX Design")),
                            react_1.default.createElement("td", { className: 'text-dark fw-bolder text-hover-primary fs-6' }, "$3560"),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("span", { className: 'badge badge-light-success' }, "Approved")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input widget-13-check', type: 'checkbox', value: '1' }))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary fs-6' }, "05822-FXSP")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Belarus"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Code: BY")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "04/18/2021"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Code: Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Agoda"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Houses & Hotels")),
                            react_1.default.createElement("td", { className: 'text-dark fw-bolder text-hover-primary fs-6' }, "$4850"),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("span", { className: 'badge badge-light-warning' }, "In Progress")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input widget-13-check', type: 'checkbox', value: '1' }))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary fs-6' }, "4472-QREX")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Phillipines"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Code: BH")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "07/23/2019"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Code: Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "RoadGee"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Transportation")),
                            react_1.default.createElement("td", { className: 'text-dark fw-bolder text-hover-primary fs-6' }, "$8376"),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("span", { className: 'badge badge-light-danger' }, "Success")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input widget-13-check', type: 'checkbox', value: '1' }))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary fs-6' }, "00347-BCLQ")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Argentina"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Code: BR")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "12/21/2021"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Code: Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "The Hill"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Insurance")),
                            react_1.default.createElement("td", { className: 'text-dark fw-bolder text-hover-primary fs-6' }, "$9486"),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("span", { className: 'badge badge-light-info' }, "Rejected")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' })))),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'form-check form-check-sm form-check-custom form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input widget-13-check', type: 'checkbox', value: '1' }))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary fs-6' }, "59486-XDER")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Agoda"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Code: BT")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "05/28/2020"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Code: Paid")),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary d-block mb-1 fs-6' }, "Phillipines"),
                                react_1.default.createElement("span", { className: 'text-muted fw-bold text-muted d-block fs-7' }, "Transportation")),
                            react_1.default.createElement("td", { className: 'text-dark fw-bolder text-hover-primary fs-6' }, "$8476"),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("span", { className: 'badge badge-light-primary' }, "Approved")),
                            react_1.default.createElement("td", { className: 'text-end' },
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen019.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/art/art005.svg', className: 'svg-icon-3' })),
                                react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-bg-light btn-active-color-primary btn-sm' },
                                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen027.svg', className: 'svg-icon-3' }))))))))));
};
exports.TablesWidget13 = TablesWidget13;
