"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TablesWidget6 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var TablesWidget6 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: "card ".concat(className) },
        react_1.default.createElement("div", { className: 'card-header border-0 pt-5' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'card-label fw-bolder fs-3 mb-1' }, "Authors Earnings"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "More than 400 new authors")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("ul", { className: 'nav' },
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary active fw-bolder px-4 me-1', "data-bs-toggle": 'tab', href: '#kt_table_widget_6_tab_1' }, "Month")),
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary fw-bolder px-4 me-1', "data-bs-toggle": 'tab', href: '#kt_table_widget_6_tab_2' }, "Week")),
                    react_1.default.createElement("li", { className: 'nav-item' },
                        react_1.default.createElement("a", { className: 'nav-link btn btn-sm btn-color-muted btn-active btn-active-light-primary fw-bolder px-4', "data-bs-toggle": 'tab', href: '#kt_table_widget_6_tab_3' }, "Day"))))),
        react_1.default.createElement("div", { className: 'card-body py-3' },
            react_1.default.createElement("div", { className: 'tab-content' },
                react_1.default.createElement("div", { className: 'tab-pane fade show active', id: 'kt_table_widget_6_tab_1' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-3' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-140px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-120px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/001-boy.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Brad Simmons"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Successful Fellas")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$200,500")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-primary fs-7 fw-bolder' }, "+28%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/018-girl-9.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Jessie Clarcson"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "HTML, CSS Coding")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$1,200,000")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-warning fs-7 fw-bolder' }, "+52%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/047-girl-25.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Jessie Clarcson"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "PHP, Laravel, VueJS")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$1,200,000")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-danger fs-7 fw-bolder' }, "+52%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/014-girl-7.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Natali Trump"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "UI/UX Designer")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$3,400,000")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-success fs-7 fw-bolder' }, "-34%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/043-boy-18.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Kevin Leonard"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Art Director")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$35,600,000")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-info fs-7 fw-bolder' }, "+230%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))))))),
                react_1.default.createElement("div", { className: 'tab-pane fade', id: 'kt_table_widget_6_tab_2' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-3' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-140px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-120px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/018-girl-9.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Jessie Clarcson"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "HTML, CSS Coding")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$1,200,000")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-warning fs-7 fw-bolder' }, "+52%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/014-girl-7.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Natali Trump"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "UI/UX Designer")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$3,400,000")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-success fs-7 fw-bolder' }, "-34%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/001-boy.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Brad Simmons"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Successful Fellas")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$200,500")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-primary fs-7 fw-bolder' }, "+28%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))))))),
                react_1.default.createElement("div", { className: 'tab-pane fade', id: 'kt_table_widget_6_tab_3' },
                    react_1.default.createElement("div", { className: 'table-responsive' },
                        react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-3' },
                            react_1.default.createElement("thead", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-140px' }),
                                    react_1.default.createElement("th", { className: 'p-0 min-w-120px' }))),
                            react_1.default.createElement("tbody", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/047-girl-25.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Jessie Clarcson"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "HTML, CSS Coding")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$1,200,000")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-danger fs-7 fw-bolder' }, "+52%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/014-girl-7.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Natali Trump"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "UI/UX Designer")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$3,400,000")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-success fs-7 fw-bolder' }, "-34%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/043-boy-18.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Kevin Leonard"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Art Director")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$35,600,000")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-info fs-7 fw-bolder' }, "+230%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' })))),
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                            react_1.default.createElement("span", { className: 'symbol-label' },
                                                react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/avatars/001-boy.svg'), className: 'h-75 align-self-end', alt: '' })))),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Brad Simmons"),
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block' }, "Successful Fellas")),
                                    react_1.default.createElement("td", null,
                                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Paid"),
                                        react_1.default.createElement("span", { className: 'text-dark fw-bolder d-block fs-5' }, "$200,500")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("span", { className: 'text-primary fs-7 fw-bolder' }, "+28%")),
                                    react_1.default.createElement("td", { className: 'text-end' },
                                        react_1.default.createElement("a", { href: '#', className: 'btn btn-sm btn-icon btn-bg-light btn-active-color-primary' },
                                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2' }))))))))))));
};
exports.TablesWidget6 = TablesWidget6;
