"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TablesWidget3 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var Dropdown1_1 = require("../../content/dropdown/Dropdown1");
var TablesWidget3 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: "card ".concat(className) },
        react_1.default.createElement("div", { className: 'card-header border-0 pt-5' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'card-label fw-bolder fs-3 mb-1' }, "Files"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "Over 100 pending files")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("button", { type: 'button', className: 'btn btn-sm btn-icon btn-color-primary btn-active-light-primary', "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'bottom-end', "data-kt-menu-flip": 'top-end' },
                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen024.svg', className: 'svg-icon-2' })),
                react_1.default.createElement(Dropdown1_1.Dropdown1, null))),
        react_1.default.createElement("div", { className: 'card-body py-3' },
            react_1.default.createElement("div", { className: 'table-responsive' },
                react_1.default.createElement("table", { className: 'table align-middle gs-0 gy-3' },
                    react_1.default.createElement("thead", null,
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("th", { className: 'p-0 w-50px' }),
                            react_1.default.createElement("th", { className: 'p-0 min-w-150px' }),
                            react_1.default.createElement("th", { className: 'p-0 min-w-140px' }),
                            react_1.default.createElement("th", { className: 'p-0 min-w-120px' }),
                            react_1.default.createElement("th", { className: 'p-0 min-w-40px' }))),
                    react_1.default.createElement("tbody", null,
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light-success' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/ecommerce/ecm002.svg', className: 'svg-icon-2x svg-icon-success' })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Top Authors")),
                            react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "ReactJs, HTML"),
                            react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "4600 Users"),
                            react_1.default.createElement("td", { className: 'text-end text-dark fw-bolder fs-6 pe-0' }, "5.4MB")),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light-danger' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen024.svg', className: 'svg-icon-2x svg-icon-danger' })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Popular Authors")),
                            react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "Python, MySQL"),
                            react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "7200 Users"),
                            react_1.default.createElement("td", { className: 'text-end text-dark fw-bolder fs-6 pe-0' }, "2.8MB")),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light-info' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/finance/fin006.svg', className: 'svg-icon-2x svg-icon-info' })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "New Users")),
                            react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "Laravel, Metronic"),
                            react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "890 Users"),
                            react_1.default.createElement("td", { className: 'text-end text-dark fw-bolder fs-6 pe-0' }, "1.5MB")),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light-warning' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/abstract/abs027.svg', className: 'svg-icon-2x svg-icon-warning' })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Active Customers")),
                            react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "AngularJS, C#"),
                            react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "4600 Users"),
                            react_1.default.createElement("td", { className: 'text-end text-dark fw-bolder fs-6 pe-0' }, "5.4MB")),
                        react_1.default.createElement("tr", null,
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("div", { className: 'symbol symbol-50px me-2' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light-primary' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/abstract/abs042.svg', className: 'svg-icon-2x svg-icon-primar' })))),
                            react_1.default.createElement("td", null,
                                react_1.default.createElement("a", { href: '#', className: 'text-dark fw-bolder text-hover-primary mb-1 fs-6' }, "Active Customers")),
                            react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "ReactJS, Ruby"),
                            react_1.default.createElement("td", { className: 'text-end text-muted fw-bold' }, "354 Users"),
                            react_1.default.createElement("td", { className: 'text-end text-dark fw-bolder fs-6 pe-0' }, "500KB"))))))));
};
exports.TablesWidget3 = TablesWidget3;
