"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mixed = void 0;
var react_1 = require("react");
var widgets_1 = require("../../../../_metronic/partials/widgets");
var Mixed = function () {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement("div", { className: 'row g-5 g-xl-8' },
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget1, { className: 'card-xl-stretch mb-xl-8', color: 'primary' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget1, { className: 'card-xl-stretch mb-xl-8', color: 'danger' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget1, { className: 'card-xl-stretch mb-5 mb-xl-8', color: 'success' }))),
        react_1.default.createElement("div", { className: 'row g-5 g-xl-8' },
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget2, { className: 'card-xl-stretch mb-xl-8', chartColor: 'info', chartHeight: '200px', strokeColor: '#4e12c4' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget2, { className: 'card-xl-stretch mb-xl-8', chartColor: 'danger', chartHeight: '200px', strokeColor: '#cb1e46' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget2, { className: 'card-xl-stretch mb-5 mb-xl-8', chartColor: 'primary', chartHeight: '200px', strokeColor: '#0078d0' }))),
        react_1.default.createElement("div", { className: 'row g-5 g-xl-8' },
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget3, { className: 'card-xl-stretch mb-xl-8', chartColor: 'info', chartHeight: '250px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget3, { className: 'card-xl-stretch mb-xl-8', chartColor: 'danger', chartHeight: '250px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget3, { className: 'card-xl-stretch mb-5 mb-xl-8', chartColor: 'primary', chartHeight: '250px' }))),
        react_1.default.createElement("div", { className: 'row g-5 g-xl-8' },
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget4, { className: 'card-xl-stretch mb-xl-8', image: '/media/svg/brand-logos/plurk.svg', color: 'danger', title: 'Monthly Subscription', date: 'Due: 27 Apr 2020', progress: '75%' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget4, { className: 'card-xl-stretch mb-xl-8', image: '/media/svg/brand-logos/vimeo.svg', color: 'primary', title: 'Monthly Subscription', date: 'Due: 27 Apr 2020', progress: '75%' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget4, { className: 'card-xl-stretch mb-5 mb-xl-8', image: '/media/svg/brand-logos/kickstarter.svg', color: 'success', title: 'Monthly Subscription', date: 'Due: 27 Apr 2020', progress: '75%' }))),
        react_1.default.createElement("div", { className: 'row g-5 g-xl-8' },
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget5, { className: 'card-xl-stretch mb-xl-8', image: '/media/svg/brand-logos/plurk.svg', time: '7 hours ago', title: 'PitStop - Multiple Email Generator', description: 'Pitstop creates quick email campaigns.<br/>We help to strengthen your brand<br/>for your every purpose.' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget5, { className: 'card-xl-stretch mb-xl-8', image: '/media/svg/brand-logos/telegram.svg', time: '10 days ago', title: 'ReactJS Admin Theme', description: 'Keenthemes uses the latest and greatest frameworks<br/>with ReactJS for complete modernization and<br/>future.' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget5, { className: 'card-xl-stretch mb-5 mb-xl-8', image: '/media/svg/brand-logos/vimeo.svg', time: '2 weeks ago', title: 'KT.com - High Quality Templates', description: 'Easy to use, incredibly flexible and secure<br/>with in-depth documentation that outlines<br/>everything for you' }))),
        react_1.default.createElement("div", { className: 'row g-5 g-xl-8' },
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget6, { className: 'card-xl-stretch mb-xl-8', chartColor: 'primary', chartHeight: '150px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget6, { className: 'card-xl-stretch mb-xl-8', chartColor: 'danger', chartHeight: '150px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget6, { className: 'card-xl-stretch mb-5 mb-xl-8', chartColor: 'success', chartHeight: '150px' }))),
        react_1.default.createElement("div", { className: 'row g-5 g-xl-8' },
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget7, { className: 'card-xl-stretch mb-xl-8', chartColor: 'primary', chartHeight: '200px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget7, { className: 'card-xl-stretch mb-xl-8', chartColor: 'success', chartHeight: '200px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget7, { className: 'card-xl-stretch mb-xl-8', chartColor: 'danger', chartHeight: '200px' }))),
        react_1.default.createElement("div", { className: 'row g-5 g-xl-8' },
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget8, { className: 'card-xl-stretch mb-xl-8', chartColor: 'primary', chartHeight: '150px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget8, { className: 'card-xl-stretch mb-xl-8', chartColor: 'success', chartHeight: '150px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget8, { className: 'card-xl-stretch mb-5 mb-xl-8', chartColor: 'danger', chartHeight: '150px' }))),
        react_1.default.createElement("div", { className: 'row g-5 g-xl-8' },
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget9, { className: 'card-xl-stretch mb-xl-8', chartColor: 'primary', chartHeight: '150px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget9, { className: 'card-xl-stretch mb-xl-8', chartColor: 'success', chartHeight: '150px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget9, { className: 'card-xl-stretch mb-xl-8', chartColor: 'danger', chartHeight: '150px' }))),
        react_1.default.createElement("div", { className: 'row g-5 g-xl-8' },
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget10, { className: 'card-xl-stretch mb-xl-8', chartColor: 'info', chartHeight: '150px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget10, { className: 'card-xl-stretch mb-xl-8', chartColor: 'warning', chartHeight: '150px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget10, { className: 'card-xl-stretch mb-5 mb-xl-8', chartColor: 'primary', chartHeight: '150px' }))),
        react_1.default.createElement("div", { className: 'row g-5 g-xl-8' },
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget11, { className: 'card-xl-stretch mb-xl-8', chartColor: 'info', chartHeight: '200px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget11, { className: 'card-xl-stretch mb-xl-8', chartColor: 'warning', chartHeight: '200px' })),
            react_1.default.createElement("div", { className: 'col-xl-4' },
                react_1.default.createElement(widgets_1.MixedWidget11, { className: 'card-xl-stretch mb-xl-8', chartColor: 'primary', chartHeight: '200px' })))));
};
exports.Mixed = Mixed;
