"use strict";
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProfileDetails = void 0;
var react_1 = require("react");
var helpers_1 = require("../../../../../../_metronic/helpers");
var SettingsModel_1 = require("../SettingsModel");
var Yup = require("yup");
var formik_1 = require("formik");
var profileDetailsSchema = Yup.object().shape({
    fName: Yup.string().required('First name is required'),
    lName: Yup.string().required('Last name is required'),
    company: Yup.string().required('Company name is required'),
    contactPhone: Yup.string().required('Contact phone is required'),
    companySite: Yup.string().required('Company site is required'),
    country: Yup.string().required('Country is required'),
    language: Yup.string().required('Language is required'),
    timeZone: Yup.string().required('Time zone is required'),
    currency: Yup.string().required('Currency is required'),
});
var ProfileDetails = function () {
    var _a, _b;
    var _c = (0, react_1.useState)(SettingsModel_1.profileDetailsInitValues), data = _c[0], setData = _c[1];
    var updateData = function (fieldsToUpdate) {
        var updatedData = Object.assign(data, fieldsToUpdate);
        setData(updatedData);
    };
    var _d = (0, react_1.useState)(false), loading = _d[0], setLoading = _d[1];
    var formik = (0, formik_1.useFormik)({
        initialValues: SettingsModel_1.profileDetailsInitValues,
        validationSchema: profileDetailsSchema,
        onSubmit: function (values) {
            setLoading(true);
            setTimeout(function () {
                values.communications.email = data.communications.email;
                values.communications.phone = data.communications.phone;
                values.allowMarketing = data.allowMarketing;
                var updatedData = Object.assign(data, values);
                setData(updatedData);
                setLoading(false);
            }, 1000);
        },
    });
    return (react_1.default.createElement("div", { className: 'card mb-5 mb-xl-10' },
        react_1.default.createElement("div", { className: 'card-header border-0 cursor-pointer', role: 'button', "data-bs-toggle": 'collapse', "data-bs-target": '#kt_account_profile_details', "aria-expanded": 'true', "aria-controls": 'kt_account_profile_details' },
            react_1.default.createElement("div", { className: 'card-title m-0' },
                react_1.default.createElement("h3", { className: 'fw-bolder m-0' }, "Profile Details"))),
        react_1.default.createElement("div", { id: 'kt_account_profile_details', className: 'collapse show' },
            react_1.default.createElement("form", { onSubmit: formik.handleSubmit, noValidate: true, className: 'form' },
                react_1.default.createElement("div", { className: 'card-body border-top p-9' },
                    react_1.default.createElement("div", { className: 'row mb-6' },
                        react_1.default.createElement("label", { className: 'col-lg-4 col-form-label fw-bold fs-6' }, "Avatar"),
                        react_1.default.createElement("div", { className: 'col-lg-8' },
                            react_1.default.createElement("div", { className: 'image-input image-input-outline', "data-kt-image-input": 'true', style: { backgroundImage: "url(".concat((0, helpers_1.toAbsoluteUrl)('/media/avatars/blank.png'), ")") } },
                                react_1.default.createElement("div", { className: 'image-input-wrapper w-125px h-125px', style: { backgroundImage: "url(".concat((0, helpers_1.toAbsoluteUrl)(data.avatar), ")") } })))),
                    react_1.default.createElement("div", { className: 'row mb-6' },
                        react_1.default.createElement("label", { className: 'col-lg-4 col-form-label required fw-bold fs-6' }, "Full Name"),
                        react_1.default.createElement("div", { className: 'col-lg-8' },
                            react_1.default.createElement("div", { className: 'row' },
                                react_1.default.createElement("div", { className: 'col-lg-6 fv-row' },
                                    react_1.default.createElement("input", __assign({ type: 'text', className: 'form-control form-control-lg form-control-solid mb-3 mb-lg-0', placeholder: 'First name' }, formik.getFieldProps('fName'))),
                                    formik.touched.fName && formik.errors.fName && (react_1.default.createElement("div", { className: 'fv-plugins-message-container' },
                                        react_1.default.createElement("div", { className: 'fv-help-block' }, formik.errors.fName)))),
                                react_1.default.createElement("div", { className: 'col-lg-6 fv-row' },
                                    react_1.default.createElement("input", __assign({ type: 'text', className: 'form-control form-control-lg form-control-solid', placeholder: 'Last name' }, formik.getFieldProps('lName'))),
                                    formik.touched.lName && formik.errors.lName && (react_1.default.createElement("div", { className: 'fv-plugins-message-container' },
                                        react_1.default.createElement("div", { className: 'fv-help-block' }, formik.errors.lName))))))),
                    react_1.default.createElement("div", { className: 'row mb-6' },
                        react_1.default.createElement("label", { className: 'col-lg-4 col-form-label required fw-bold fs-6' }, "Company"),
                        react_1.default.createElement("div", { className: 'col-lg-8 fv-row' },
                            react_1.default.createElement("input", __assign({ type: 'text', className: 'form-control form-control-lg form-control-solid', placeholder: 'Company name' }, formik.getFieldProps('company'))),
                            formik.touched.company && formik.errors.company && (react_1.default.createElement("div", { className: 'fv-plugins-message-container' },
                                react_1.default.createElement("div", { className: 'fv-help-block' }, formik.errors.company))))),
                    react_1.default.createElement("div", { className: 'row mb-6' },
                        react_1.default.createElement("label", { className: 'col-lg-4 col-form-label fw-bold fs-6' },
                            react_1.default.createElement("span", { className: 'required' }, "Contact Phone")),
                        react_1.default.createElement("div", { className: 'col-lg-8 fv-row' },
                            react_1.default.createElement("input", __assign({ type: 'tel', className: 'form-control form-control-lg form-control-solid', placeholder: 'Phone number' }, formik.getFieldProps('contactPhone'))),
                            formik.touched.contactPhone && formik.errors.contactPhone && (react_1.default.createElement("div", { className: 'fv-plugins-message-container' },
                                react_1.default.createElement("div", { className: 'fv-help-block' }, formik.errors.contactPhone))))),
                    react_1.default.createElement("div", { className: 'row mb-6' },
                        react_1.default.createElement("label", { className: 'col-lg-4 col-form-label fw-bold fs-6' },
                            react_1.default.createElement("span", { className: 'required' }, "Company Site")),
                        react_1.default.createElement("div", { className: 'col-lg-8 fv-row' },
                            react_1.default.createElement("input", __assign({ type: 'text', className: 'form-control form-control-lg form-control-solid', placeholder: 'Company website' }, formik.getFieldProps('companySite'))),
                            formik.touched.companySite && formik.errors.companySite && (react_1.default.createElement("div", { className: 'fv-plugins-message-container' },
                                react_1.default.createElement("div", { className: 'fv-help-block' }, formik.errors.companySite))))),
                    react_1.default.createElement("div", { className: 'row mb-6' },
                        react_1.default.createElement("label", { className: 'col-lg-4 col-form-label fw-bold fs-6' },
                            react_1.default.createElement("span", { className: 'required' }, "Country")),
                        react_1.default.createElement("div", { className: 'col-lg-8 fv-row' },
                            react_1.default.createElement("select", __assign({ className: 'form-select form-select-solid form-select-lg fw-bold' }, formik.getFieldProps('country')),
                                react_1.default.createElement("option", { value: '' }, "Select a Country..."),
                                react_1.default.createElement("option", { value: 'AF' }, "Afghanistan"),
                                react_1.default.createElement("option", { value: 'AX' }, "Aland Islands"),
                                react_1.default.createElement("option", { value: 'AL' }, "Albania"),
                                react_1.default.createElement("option", { value: 'DZ' }, "Algeria"),
                                react_1.default.createElement("option", { value: 'AS' }, "American Samoa"),
                                react_1.default.createElement("option", { value: 'AD' }, "Andorra"),
                                react_1.default.createElement("option", { value: 'AO' }, "Angola"),
                                react_1.default.createElement("option", { value: 'AI' }, "Anguilla"),
                                react_1.default.createElement("option", { value: 'AQ' }, "Antarctica"),
                                react_1.default.createElement("option", { value: 'AG' }, "Antigua and Barbuda"),
                                react_1.default.createElement("option", { value: 'AR' }, "Argentina"),
                                react_1.default.createElement("option", { value: 'AM' }, "Armenia"),
                                react_1.default.createElement("option", { value: 'AW' }, "Aruba"),
                                react_1.default.createElement("option", { value: 'AU' }, "Australia"),
                                react_1.default.createElement("option", { value: 'AT' }, "Austria"),
                                react_1.default.createElement("option", { value: 'AZ' }, "Azerbaijan"),
                                react_1.default.createElement("option", { value: 'BS' }, "Bahamas"),
                                react_1.default.createElement("option", { value: 'BH' }, "Bahrain"),
                                react_1.default.createElement("option", { value: 'BD' }, "Bangladesh"),
                                react_1.default.createElement("option", { value: 'BB' }, "Barbados"),
                                react_1.default.createElement("option", { value: 'BY' }, "Belarus"),
                                react_1.default.createElement("option", { value: 'BE' }, "Belgium"),
                                react_1.default.createElement("option", { value: 'BZ' }, "Belize"),
                                react_1.default.createElement("option", { value: 'BJ' }, "Benin"),
                                react_1.default.createElement("option", { value: 'BM' }, "Bermuda"),
                                react_1.default.createElement("option", { value: 'BT' }, "Bhutan"),
                                react_1.default.createElement("option", { value: 'BO' }, "Bolivia, Plurinational State of"),
                                react_1.default.createElement("option", { value: 'BQ' }, "Bonaire, Sint Eustatius and Saba"),
                                react_1.default.createElement("option", { value: 'BA' }, "Bosnia and Herzegovina"),
                                react_1.default.createElement("option", { value: 'BW' }, "Botswana"),
                                react_1.default.createElement("option", { value: 'BV' }, "Bouvet Island"),
                                react_1.default.createElement("option", { value: 'BR' }, "Brazil"),
                                react_1.default.createElement("option", { value: 'IO' }, "British Indian Ocean Territory"),
                                react_1.default.createElement("option", { value: 'BN' }, "Brunei Darussalam"),
                                react_1.default.createElement("option", { value: 'BG' }, "Bulgaria"),
                                react_1.default.createElement("option", { value: 'BF' }, "Burkina Faso"),
                                react_1.default.createElement("option", { value: 'BI' }, "Burundi"),
                                react_1.default.createElement("option", { value: 'KH' }, "Cambodia"),
                                react_1.default.createElement("option", { value: 'CM' }, "Cameroon"),
                                react_1.default.createElement("option", { value: 'CA' }, "Canada"),
                                react_1.default.createElement("option", { value: 'CV' }, "Cape Verde"),
                                react_1.default.createElement("option", { value: 'KY' }, "Cayman Islands"),
                                react_1.default.createElement("option", { value: 'CF' }, "Central African Republic"),
                                react_1.default.createElement("option", { value: 'TD' }, "Chad"),
                                react_1.default.createElement("option", { value: 'CL' }, "Chile"),
                                react_1.default.createElement("option", { value: 'CN' }, "China"),
                                react_1.default.createElement("option", { value: 'CX' }, "Christmas Island"),
                                react_1.default.createElement("option", { value: 'CC' }, "Cocos (Keeling) Islands"),
                                react_1.default.createElement("option", { value: 'CO' }, "Colombia"),
                                react_1.default.createElement("option", { value: 'KM' }, "Comoros"),
                                react_1.default.createElement("option", { value: 'CG' }, "Congo"),
                                react_1.default.createElement("option", { value: 'CD' }, "Congo, the Democratic Republic of the"),
                                react_1.default.createElement("option", { value: 'CK' }, "Cook Islands"),
                                react_1.default.createElement("option", { value: 'CR' }, "Costa Rica"),
                                react_1.default.createElement("option", { value: 'CI' }, "C\u00F4te d'Ivoire"),
                                react_1.default.createElement("option", { value: 'HR' }, "Croatia"),
                                react_1.default.createElement("option", { value: 'CU' }, "Cuba"),
                                react_1.default.createElement("option", { value: 'CW' }, "Cura\u00E7ao"),
                                react_1.default.createElement("option", { value: 'CY' }, "Cyprus"),
                                react_1.default.createElement("option", { value: 'CZ' }, "Czech Republic"),
                                react_1.default.createElement("option", { value: 'DK' }, "Denmark"),
                                react_1.default.createElement("option", { value: 'DJ' }, "Djibouti"),
                                react_1.default.createElement("option", { value: 'DM' }, "Dominica"),
                                react_1.default.createElement("option", { value: 'DO' }, "Dominican Republic"),
                                react_1.default.createElement("option", { value: 'EC' }, "Ecuador"),
                                react_1.default.createElement("option", { value: 'EG' }, "Egypt"),
                                react_1.default.createElement("option", { value: 'SV' }, "El Salvador"),
                                react_1.default.createElement("option", { value: 'GQ' }, "Equatorial Guinea"),
                                react_1.default.createElement("option", { value: 'ER' }, "Eritrea"),
                                react_1.default.createElement("option", { value: 'EE' }, "Estonia"),
                                react_1.default.createElement("option", { value: 'ET' }, "Ethiopia"),
                                react_1.default.createElement("option", { value: 'FK' }, "Falkland Islands (Malvinas)"),
                                react_1.default.createElement("option", { value: 'FO' }, "Faroe Islands"),
                                react_1.default.createElement("option", { value: 'FJ' }, "Fiji"),
                                react_1.default.createElement("option", { value: 'FI' }, "Finland"),
                                react_1.default.createElement("option", { value: 'FR' }, "France"),
                                react_1.default.createElement("option", { value: 'GF' }, "French Guiana"),
                                react_1.default.createElement("option", { value: 'PF' }, "French Polynesia"),
                                react_1.default.createElement("option", { value: 'TF' }, "French Southern Territories"),
                                react_1.default.createElement("option", { value: 'GA' }, "Gabon"),
                                react_1.default.createElement("option", { value: 'GM' }, "Gambia"),
                                react_1.default.createElement("option", { value: 'GE' }, "Georgia"),
                                react_1.default.createElement("option", { value: 'DE' }, "Germany"),
                                react_1.default.createElement("option", { value: 'GH' }, "Ghana"),
                                react_1.default.createElement("option", { value: 'GI' }, "Gibraltar"),
                                react_1.default.createElement("option", { value: 'GR' }, "Greece"),
                                react_1.default.createElement("option", { value: 'GL' }, "Greenland"),
                                react_1.default.createElement("option", { value: 'GD' }, "Grenada"),
                                react_1.default.createElement("option", { value: 'GP' }, "Guadeloupe"),
                                react_1.default.createElement("option", { value: 'GU' }, "Guam"),
                                react_1.default.createElement("option", { value: 'GT' }, "Guatemala"),
                                react_1.default.createElement("option", { value: 'GG' }, "Guernsey"),
                                react_1.default.createElement("option", { value: 'GN' }, "Guinea"),
                                react_1.default.createElement("option", { value: 'GW' }, "Guinea-Bissau"),
                                react_1.default.createElement("option", { value: 'GY' }, "Guyana"),
                                react_1.default.createElement("option", { value: 'HT' }, "Haiti"),
                                react_1.default.createElement("option", { value: 'HM' }, "Heard Island and McDonald Islands"),
                                react_1.default.createElement("option", { value: 'VA' }, "Holy See (Vatican City State)"),
                                react_1.default.createElement("option", { value: 'HN' }, "Honduras"),
                                react_1.default.createElement("option", { value: 'HK' }, "Hong Kong"),
                                react_1.default.createElement("option", { value: 'HU' }, "Hungary"),
                                react_1.default.createElement("option", { value: 'IS' }, "Iceland"),
                                react_1.default.createElement("option", { value: 'IN' }, "India"),
                                react_1.default.createElement("option", { value: 'ID' }, "Indonesia"),
                                react_1.default.createElement("option", { value: 'IR' }, "Iran, Islamic Republic of"),
                                react_1.default.createElement("option", { value: 'IQ' }, "Iraq"),
                                react_1.default.createElement("option", { value: 'IE' }, "Ireland"),
                                react_1.default.createElement("option", { value: 'IM' }, "Isle of Man"),
                                react_1.default.createElement("option", { value: 'IL' }, "Israel"),
                                react_1.default.createElement("option", { value: 'IT' }, "Italy"),
                                react_1.default.createElement("option", { value: 'JM' }, "Jamaica"),
                                react_1.default.createElement("option", { value: 'JP' }, "Japan"),
                                react_1.default.createElement("option", { value: 'JE' }, "Jersey"),
                                react_1.default.createElement("option", { value: 'JO' }, "Jordan"),
                                react_1.default.createElement("option", { value: 'KZ' }, "Kazakhstan"),
                                react_1.default.createElement("option", { value: 'KE' }, "Kenya"),
                                react_1.default.createElement("option", { value: 'KI' }, "Kiribati"),
                                react_1.default.createElement("option", { value: 'KP' }, "Korea, Democratic People's Republic of"),
                                react_1.default.createElement("option", { value: 'KW' }, "Kuwait"),
                                react_1.default.createElement("option", { value: 'KG' }, "Kyrgyzstan"),
                                react_1.default.createElement("option", { value: 'LA' }, "Lao People's Democratic Republic"),
                                react_1.default.createElement("option", { value: 'LV' }, "Latvia"),
                                react_1.default.createElement("option", { value: 'LB' }, "Lebanon"),
                                react_1.default.createElement("option", { value: 'LS' }, "Lesotho"),
                                react_1.default.createElement("option", { value: 'LR' }, "Liberia"),
                                react_1.default.createElement("option", { value: 'LY' }, "Libya"),
                                react_1.default.createElement("option", { value: 'LI' }, "Liechtenstein"),
                                react_1.default.createElement("option", { value: 'LT' }, "Lithuania"),
                                react_1.default.createElement("option", { value: 'LU' }, "Luxembourg"),
                                react_1.default.createElement("option", { value: 'MO' }, "Macao"),
                                react_1.default.createElement("option", { value: 'MK' }, "Macedonia, the former Yugoslav Republic of"),
                                react_1.default.createElement("option", { value: 'MG' }, "Madagascar"),
                                react_1.default.createElement("option", { value: 'MW' }, "Malawi"),
                                react_1.default.createElement("option", { value: 'MY' }, "Malaysia"),
                                react_1.default.createElement("option", { value: 'MV' }, "Maldives"),
                                react_1.default.createElement("option", { value: 'ML' }, "Mali"),
                                react_1.default.createElement("option", { value: 'MT' }, "Malta"),
                                react_1.default.createElement("option", { value: 'MH' }, "Marshall Islands"),
                                react_1.default.createElement("option", { value: 'MQ' }, "Martinique"),
                                react_1.default.createElement("option", { value: 'MR' }, "Mauritania"),
                                react_1.default.createElement("option", { value: 'MU' }, "Mauritius"),
                                react_1.default.createElement("option", { value: 'YT' }, "Mayotte"),
                                react_1.default.createElement("option", { value: 'MX' }, "Mexico"),
                                react_1.default.createElement("option", { value: 'FM' }, "Micronesia, Federated States of"),
                                react_1.default.createElement("option", { value: 'MD' }, "Moldova, Republic of"),
                                react_1.default.createElement("option", { value: 'MC' }, "Monaco"),
                                react_1.default.createElement("option", { value: 'MN' }, "Mongolia"),
                                react_1.default.createElement("option", { value: 'ME' }, "Montenegro"),
                                react_1.default.createElement("option", { value: 'MS' }, "Montserrat"),
                                react_1.default.createElement("option", { value: 'MA' }, "Morocco"),
                                react_1.default.createElement("option", { value: 'MZ' }, "Mozambique"),
                                react_1.default.createElement("option", { value: 'MM' }, "Myanmar"),
                                react_1.default.createElement("option", { value: 'NA' }, "Namibia"),
                                react_1.default.createElement("option", { value: 'NR' }, "Nauru"),
                                react_1.default.createElement("option", { value: 'NP' }, "Nepal"),
                                react_1.default.createElement("option", { value: 'NL' }, "Netherlands"),
                                react_1.default.createElement("option", { value: 'NC' }, "New Caledonia"),
                                react_1.default.createElement("option", { value: 'NZ' }, "New Zealand"),
                                react_1.default.createElement("option", { value: 'NI' }, "Nicaragua"),
                                react_1.default.createElement("option", { value: 'NE' }, "Niger"),
                                react_1.default.createElement("option", { value: 'NG' }, "Nigeria"),
                                react_1.default.createElement("option", { value: 'NU' }, "Niue"),
                                react_1.default.createElement("option", { value: 'NF' }, "Norfolk Island"),
                                react_1.default.createElement("option", { value: 'MP' }, "Northern Mariana Islands"),
                                react_1.default.createElement("option", { value: 'NO' }, "Norway"),
                                react_1.default.createElement("option", { value: 'OM' }, "Oman"),
                                react_1.default.createElement("option", { value: 'PK' }, "Pakistan"),
                                react_1.default.createElement("option", { value: 'PW' }, "Palau"),
                                react_1.default.createElement("option", { value: 'PS' }, "Palestinian Territory, Occupied"),
                                react_1.default.createElement("option", { value: 'PA' }, "Panama"),
                                react_1.default.createElement("option", { value: 'PG' }, "Papua New Guinea"),
                                react_1.default.createElement("option", { value: 'PY' }, "Paraguay"),
                                react_1.default.createElement("option", { value: 'PE' }, "Peru"),
                                react_1.default.createElement("option", { value: 'PH' }, "Philippines"),
                                react_1.default.createElement("option", { value: 'PN' }, "Pitcairn"),
                                react_1.default.createElement("option", { value: 'PL' }, "Poland"),
                                react_1.default.createElement("option", { value: 'PT' }, "Portugal"),
                                react_1.default.createElement("option", { value: 'PR' }, "Puerto Rico"),
                                react_1.default.createElement("option", { value: 'QA' }, "Qatar"),
                                react_1.default.createElement("option", { value: 'RE' }, "R\u00E9union"),
                                react_1.default.createElement("option", { value: 'RO' }, "Romania"),
                                react_1.default.createElement("option", { value: 'RU' }, "Russian Federation"),
                                react_1.default.createElement("option", { value: 'RW' }, "Rwanda"),
                                react_1.default.createElement("option", { value: 'BL' }, "Saint Barth\u00E9lemy"),
                                react_1.default.createElement("option", { value: 'SH' }, "Saint Helena, Ascension and Tristan da Cunha"),
                                react_1.default.createElement("option", { value: 'KN' }, "Saint Kitts and Nevis"),
                                react_1.default.createElement("option", { value: 'LC' }, "Saint Lucia"),
                                react_1.default.createElement("option", { value: 'MF' }, "Saint Martin (French part)"),
                                react_1.default.createElement("option", { value: 'PM' }, "Saint Pierre and Miquelon"),
                                react_1.default.createElement("option", { value: 'VC' }, "Saint Vincent and the Grenadines"),
                                react_1.default.createElement("option", { value: 'WS' }, "Samoa"),
                                react_1.default.createElement("option", { value: 'SM' }, "San Marino"),
                                react_1.default.createElement("option", { value: 'ST' }, "Sao Tome and Principe"),
                                react_1.default.createElement("option", { value: 'SA' }, "Saudi Arabia"),
                                react_1.default.createElement("option", { value: 'SN' }, "Senegal"),
                                react_1.default.createElement("option", { value: 'RS' }, "Serbia"),
                                react_1.default.createElement("option", { value: 'SC' }, "Seychelles"),
                                react_1.default.createElement("option", { value: 'SL' }, "Sierra Leone"),
                                react_1.default.createElement("option", { value: 'SG' }, "Singapore"),
                                react_1.default.createElement("option", { value: 'SX' }, "Sint Maarten (Dutch part)"),
                                react_1.default.createElement("option", { value: 'SK' }, "Slovakia"),
                                react_1.default.createElement("option", { value: 'SI' }, "Slovenia"),
                                react_1.default.createElement("option", { value: 'SB' }, "Solomon Islands"),
                                react_1.default.createElement("option", { value: 'SO' }, "Somalia"),
                                react_1.default.createElement("option", { value: 'ZA' }, "South Africa"),
                                react_1.default.createElement("option", { value: 'GS' }, "South Georgia and the South Sandwich Islands"),
                                react_1.default.createElement("option", { value: 'KR' }, "South Korea"),
                                react_1.default.createElement("option", { value: 'SS' }, "South Sudan"),
                                react_1.default.createElement("option", { value: 'ES' }, "Spain"),
                                react_1.default.createElement("option", { value: 'LK' }, "Sri Lanka"),
                                react_1.default.createElement("option", { value: 'SD' }, "Sudan"),
                                react_1.default.createElement("option", { value: 'SR' }, "Suriname"),
                                react_1.default.createElement("option", { value: 'SJ' }, "Svalbard and Jan Mayen"),
                                react_1.default.createElement("option", { value: 'SZ' }, "Swaziland"),
                                react_1.default.createElement("option", { value: 'SE' }, "Sweden"),
                                react_1.default.createElement("option", { value: 'CH' }, "Switzerland"),
                                react_1.default.createElement("option", { value: 'SY' }, "Syrian Arab Republic"),
                                react_1.default.createElement("option", { value: 'TW' }, "Taiwan, Province of China"),
                                react_1.default.createElement("option", { value: 'TJ' }, "Tajikistan"),
                                react_1.default.createElement("option", { value: 'TZ' }, "Tanzania, United Republic of"),
                                react_1.default.createElement("option", { value: 'TH' }, "Thailand"),
                                react_1.default.createElement("option", { value: 'TL' }, "Timor-Leste"),
                                react_1.default.createElement("option", { value: 'TG' }, "Togo"),
                                react_1.default.createElement("option", { value: 'TK' }, "Tokelau"),
                                react_1.default.createElement("option", { value: 'TO' }, "Tonga"),
                                react_1.default.createElement("option", { value: 'TT' }, "Trinidad and Tobago"),
                                react_1.default.createElement("option", { value: 'TN' }, "Tunisia"),
                                react_1.default.createElement("option", { value: 'TR' }, "Turkey"),
                                react_1.default.createElement("option", { value: 'TM' }, "Turkmenistan"),
                                react_1.default.createElement("option", { value: 'TC' }, "Turks and Caicos Islands"),
                                react_1.default.createElement("option", { value: 'TV' }, "Tuvalu"),
                                react_1.default.createElement("option", { value: 'UG' }, "Uganda"),
                                react_1.default.createElement("option", { value: 'UA' }, "Ukraine"),
                                react_1.default.createElement("option", { value: 'AE' }, "United Arab Emirates"),
                                react_1.default.createElement("option", { value: 'GB' }, "United Kingdom"),
                                react_1.default.createElement("option", { value: 'US' }, "United States"),
                                react_1.default.createElement("option", { value: 'UY' }, "Uruguay"),
                                react_1.default.createElement("option", { value: 'UZ' }, "Uzbekistan"),
                                react_1.default.createElement("option", { value: 'VU' }, "Vanuatu"),
                                react_1.default.createElement("option", { value: 'VE' }, "Venezuela, Bolivarian Republic of"),
                                react_1.default.createElement("option", { value: 'VN' }, "Vietnam"),
                                react_1.default.createElement("option", { value: 'VI' }, "Virgin Islands"),
                                react_1.default.createElement("option", { value: 'WF' }, "Wallis and Futuna"),
                                react_1.default.createElement("option", { value: 'EH' }, "Western Sahara"),
                                react_1.default.createElement("option", { value: 'YE' }, "Yemen"),
                                react_1.default.createElement("option", { value: 'ZM' }, "Zambia"),
                                react_1.default.createElement("option", { value: 'ZW' }, "Zimbabwe")),
                            formik.touched.country && formik.errors.country && (react_1.default.createElement("div", { className: 'fv-plugins-message-container' },
                                react_1.default.createElement("div", { className: 'fv-help-block' }, formik.errors.country))))),
                    react_1.default.createElement("div", { className: 'row mb-6' },
                        react_1.default.createElement("label", { className: 'col-lg-4 col-form-label required fw-bold fs-6' }, "Language"),
                        react_1.default.createElement("div", { className: 'col-lg-8 fv-row' },
                            react_1.default.createElement("select", __assign({ className: 'form-select form-select-solid form-select-lg' }, formik.getFieldProps('language')),
                                react_1.default.createElement("option", { value: '' }, "Select a Language..."),
                                react_1.default.createElement("option", { value: 'id' }, "Bahasa Indonesia - Indonesian"),
                                react_1.default.createElement("option", { value: 'msa' }, "Bahasa Melayu - Malay"),
                                react_1.default.createElement("option", { value: 'ca' }, "Catal\u00E0 - Catalan"),
                                react_1.default.createElement("option", { value: 'cs' }, "\u010Ce\u0161tina - Czech"),
                                react_1.default.createElement("option", { value: 'da' }, "Dansk - Danish"),
                                react_1.default.createElement("option", { value: 'de' }, "Deutsch - German"),
                                react_1.default.createElement("option", { value: 'en' }, "English"),
                                react_1.default.createElement("option", { value: 'en-gb' }, "English UK - British English"),
                                react_1.default.createElement("option", { value: 'es' }, "Espa\u00F1ol - Spanish"),
                                react_1.default.createElement("option", { value: 'fil' }, "Filipino"),
                                react_1.default.createElement("option", { value: 'fr' }, "Fran\u00E7ais - French"),
                                react_1.default.createElement("option", { value: 'ga' }, "Gaeilge - Irish (beta)"),
                                react_1.default.createElement("option", { value: 'gl' }, "Galego - Galician (beta)"),
                                react_1.default.createElement("option", { value: 'hr' }, "Hrvatski - Croatian"),
                                react_1.default.createElement("option", { value: 'it' }, "Italiano - Italian"),
                                react_1.default.createElement("option", { value: 'hu' }, "Magyar - Hungarian"),
                                react_1.default.createElement("option", { value: 'nl' }, "Nederlands - Dutch"),
                                react_1.default.createElement("option", { value: 'no' }, "Norsk - Norwegian"),
                                react_1.default.createElement("option", { value: 'pl' }, "Polski - Polish"),
                                react_1.default.createElement("option", { value: 'pt' }, "Portugu\u00EAs - Portuguese"),
                                react_1.default.createElement("option", { value: 'ro' }, "Rom\u00E2n\u0103 - Romanian"),
                                react_1.default.createElement("option", { value: 'sk' }, "Sloven\u010Dina - Slovak"),
                                react_1.default.createElement("option", { value: 'fi' }, "Suomi - Finnish"),
                                react_1.default.createElement("option", { value: 'sv' }, "Svenska - Swedish"),
                                react_1.default.createElement("option", { value: 'vi' }, "Ti\u1EBFng Vi\u1EC7t - Vietnamese"),
                                react_1.default.createElement("option", { value: 'tr' }, "T\u00FCrk\u00E7e - Turkish"),
                                react_1.default.createElement("option", { value: 'el' }, "\u0395\u03BB\u03BB\u03B7\u03BD\u03B9\u03BA\u03AC - Greek"),
                                react_1.default.createElement("option", { value: 'bg' }, "\u0411\u044A\u043B\u0433\u0430\u0440\u0441\u043A\u0438 \u0435\u0437\u0438\u043A - Bulgarian"),
                                react_1.default.createElement("option", { value: 'ru' }, "\u0420\u0443\u0441\u0441\u043A\u0438\u0439 - Russian"),
                                react_1.default.createElement("option", { value: 'sr' }, "\u0421\u0440\u043F\u0441\u043A\u0438 - Serbian"),
                                react_1.default.createElement("option", { value: 'uk' }, "\u0423\u043A\u0440\u0430\u0457\u043D\u0441\u044C\u043A\u0430 \u043C\u043E\u0432\u0430 - Ukrainian"),
                                react_1.default.createElement("option", { value: 'he' }, "\u05E2\u05B4\u05D1\u05B0\u05E8\u05B4\u05D9\u05EA - Hebrew"),
                                react_1.default.createElement("option", { value: 'ur' }, "\u0627\u0631\u062F\u0648 - Urdu (beta)"),
                                react_1.default.createElement("option", { value: 'ar' }, "\u0627\u0644\u0639\u0631\u0628\u064A\u0629 - Arabic"),
                                react_1.default.createElement("option", { value: 'fa' }, "\u0641\u0627\u0631\u0633\u06CC - Persian"),
                                react_1.default.createElement("option", { value: 'mr' }, "\u092E\u0930\u093E\u0920\u0940 - Marathi"),
                                react_1.default.createElement("option", { value: 'hi' }, "\u0939\u093F\u0928\u094D\u0926\u0940 - Hindi"),
                                react_1.default.createElement("option", { value: 'bn' }, "\u09AC\u09BE\u0982\u09B2\u09BE - Bangla"),
                                react_1.default.createElement("option", { value: 'gu' }, "\u0A97\u0AC1\u0A9C\u0AB0\u0ABE\u0AA4\u0AC0 - Gujarati"),
                                react_1.default.createElement("option", { value: 'ta' }, "\u0BA4\u0BAE\u0BBF\u0BB4\u0BCD - Tamil"),
                                react_1.default.createElement("option", { value: 'kn' }, "\u0C95\u0CA8\u0CCD\u0CA8\u0CA1 - Kannada"),
                                react_1.default.createElement("option", { value: 'th' }, "\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 - Thai"),
                                react_1.default.createElement("option", { value: 'ko' }, "\uD55C\uAD6D\uC5B4 - Korean"),
                                react_1.default.createElement("option", { value: 'ja' }, "\u65E5\u672C\u8A9E - Japanese"),
                                react_1.default.createElement("option", { value: 'zh-cn' }, "\u7B80\u4F53\u4E2D\u6587 - Simplified Chinese"),
                                react_1.default.createElement("option", { value: 'zh-tw' }, "\u7E41\u9AD4\u4E2D\u6587 - Traditional Chinese")),
                            formik.touched.language && formik.errors.language && (react_1.default.createElement("div", { className: 'fv-plugins-message-container' },
                                react_1.default.createElement("div", { className: 'fv-help-block' }, formik.errors.language))),
                            react_1.default.createElement("div", { className: 'form-text' }, "Please select a preferred language, including date, time, and number formatting."))),
                    react_1.default.createElement("div", { className: 'row mb-6' },
                        react_1.default.createElement("label", { className: 'col-lg-4 col-form-label required fw-bold fs-6' }, "Time Zone"),
                        react_1.default.createElement("div", { className: 'col-lg-8 fv-row' },
                            react_1.default.createElement("select", __assign({ className: 'form-select form-select-solid form-select-lg' }, formik.getFieldProps('timeZone')),
                                react_1.default.createElement("option", { value: '' }, "Select a Timezone.."),
                                react_1.default.createElement("option", { value: 'International Date Line West' }, "(GMT-11:00) International Date Line West"),
                                react_1.default.createElement("option", { value: 'Midway Island' }, "(GMT-11:00) Midway Island"),
                                react_1.default.createElement("option", { value: 'Samoa' }, "(GMT-11:00) Samoa"),
                                react_1.default.createElement("option", { value: 'Hawaii' }, "(GMT-10:00) Hawaii"),
                                react_1.default.createElement("option", { value: 'Alaska' }, "(GMT-08:00) Alaska"),
                                react_1.default.createElement("option", { value: 'Pacific Time (US & Canada)' }, "(GMT-07:00) Pacific Time (US & Canada)"),
                                react_1.default.createElement("option", { value: 'Tijuana' }, "(GMT-07:00) Tijuana"),
                                react_1.default.createElement("option", { value: 'Arizona' }, "(GMT-07:00) Arizona"),
                                react_1.default.createElement("option", { value: 'Mountain Time (US & Canada)' }, "(GMT-06:00) Mountain Time (US & Canada)"),
                                react_1.default.createElement("option", { value: 'Chihuahua' }, "(GMT-06:00) Chihuahua"),
                                react_1.default.createElement("option", { value: 'Mazatlan' }, "(GMT-06:00) Mazatlan"),
                                react_1.default.createElement("option", { value: 'Saskatchewan' }, "(GMT-06:00) Saskatchewan"),
                                react_1.default.createElement("option", { value: 'Central America' }, "(GMT-06:00) Central America"),
                                react_1.default.createElement("option", { value: 'Central Time (US & Canada)' }, "(GMT-05:00) Central Time (US & Canada)"),
                                react_1.default.createElement("option", { value: 'Guadalajara' }, "(GMT-05:00) Guadalajara"),
                                react_1.default.createElement("option", { value: 'Mexico City' }, "(GMT-05:00) Mexico City"),
                                react_1.default.createElement("option", { value: 'Monterrey' }, "(GMT-05:00) Monterrey"),
                                react_1.default.createElement("option", { value: 'Bogota' }, "(GMT-05:00) Bogota"),
                                react_1.default.createElement("option", { value: 'Lima' }, "(GMT-05:00) Lima"),
                                react_1.default.createElement("option", { value: 'Quito' }, "(GMT-05:00) Quito"),
                                react_1.default.createElement("option", { value: 'Eastern Time (US & Canada)' }, "(GMT-04:00) Eastern Time (US & Canada)"),
                                react_1.default.createElement("option", { value: 'Indiana (East)' }, "(GMT-04:00) Indiana (East)"),
                                react_1.default.createElement("option", { value: 'Caracas' }, "(GMT-04:00) Caracas"),
                                react_1.default.createElement("option", { value: 'La Paz' }, "(GMT-04:00) La Paz"),
                                react_1.default.createElement("option", { value: 'Georgetown' }, "(GMT-04:00) Georgetown"),
                                react_1.default.createElement("option", { value: 'Atlantic Time (Canada)' }, "(GMT-03:00) Atlantic Time (Canada)"),
                                react_1.default.createElement("option", { value: 'Santiago' }, "(GMT-03:00) Santiago"),
                                react_1.default.createElement("option", { value: 'Brasilia' }, "(GMT-03:00) Brasilia"),
                                react_1.default.createElement("option", { value: 'Buenos Aires' }, "(GMT-03:00) Buenos Aires"),
                                react_1.default.createElement("option", { value: 'Newfoundland' }, "(GMT-02:30) Newfoundland"),
                                react_1.default.createElement("option", { value: 'Greenland' }, "(GMT-02:00) Greenland"),
                                react_1.default.createElement("option", { value: 'Mid-Atlantic' }, "(GMT-02:00) Mid-Atlantic"),
                                react_1.default.createElement("option", { value: 'Cape Verde Is.' }, "(GMT-01:00) Cape Verde Is."),
                                react_1.default.createElement("option", { value: 'Azores' }, "(GMT) Azores"),
                                react_1.default.createElement("option", { value: 'Monrovia' }, "(GMT) Monrovia"),
                                react_1.default.createElement("option", { value: 'UTC' }, "(GMT) UTC"),
                                react_1.default.createElement("option", { value: 'Dublin' }, "(GMT+01:00) Dublin"),
                                react_1.default.createElement("option", { value: 'Edinburgh' }, "(GMT+01:00) Edinburgh"),
                                react_1.default.createElement("option", { value: 'Lisbon' }, "(GMT+01:00) Lisbon"),
                                react_1.default.createElement("option", { value: 'London' }, "(GMT+01:00) London"),
                                react_1.default.createElement("option", { value: 'Casablanca' }, "(GMT+01:00) Casablanca"),
                                react_1.default.createElement("option", { value: 'West Central Africa' }, "(GMT+01:00) West Central Africa"),
                                react_1.default.createElement("option", { value: 'Belgrade' }, "(GMT+02:00) Belgrade"),
                                react_1.default.createElement("option", { value: 'Bratislava' }, "(GMT+02:00) Bratislava"),
                                react_1.default.createElement("option", { value: 'Budapest' }, "(GMT+02:00) Budapest"),
                                react_1.default.createElement("option", { value: 'Ljubljana' }, "(GMT+02:00) Ljubljana"),
                                react_1.default.createElement("option", { value: 'Prague' }, "(GMT+02:00) Prague"),
                                react_1.default.createElement("option", { value: 'Sarajevo' }, "(GMT+02:00) Sarajevo"),
                                react_1.default.createElement("option", { value: 'Skopje' }, "(GMT+02:00) Skopje"),
                                react_1.default.createElement("option", { value: 'Warsaw' }, "(GMT+02:00) Warsaw"),
                                react_1.default.createElement("option", { value: 'Zagreb' }, "(GMT+02:00) Zagreb"),
                                react_1.default.createElement("option", { value: 'Brussels' }, "(GMT+02:00) Brussels"),
                                react_1.default.createElement("option", { value: 'Copenhagen' }, "(GMT+02:00) Copenhagen"),
                                react_1.default.createElement("option", { value: 'Madrid' }, "(GMT+02:00) Madrid"),
                                react_1.default.createElement("option", { value: 'Paris' }, "(GMT+02:00) Paris"),
                                react_1.default.createElement("option", { value: 'Amsterdam' }, "(GMT+02:00) Amsterdam"),
                                react_1.default.createElement("option", { value: 'Berlin' }, "(GMT+02:00) Berlin"),
                                react_1.default.createElement("option", { value: 'Bern' }, "(GMT+02:00) Bern"),
                                react_1.default.createElement("option", { value: 'Rome' }, "(GMT+02:00) Rome"),
                                react_1.default.createElement("option", { value: 'Stockholm' }, "(GMT+02:00) Stockholm"),
                                react_1.default.createElement("option", { value: 'Vienna' }, "(GMT+02:00) Vienna"),
                                react_1.default.createElement("option", { value: 'Cairo' }, "(GMT+02:00) Cairo"),
                                react_1.default.createElement("option", { value: 'Harare' }, "(GMT+02:00) Harare"),
                                react_1.default.createElement("option", { value: 'Pretoria' }, "(GMT+02:00) Pretoria"),
                                react_1.default.createElement("option", { value: 'Bucharest' }, "(GMT+03:00) Bucharest"),
                                react_1.default.createElement("option", { value: 'Helsinki' }, "(GMT+03:00) Helsinki"),
                                react_1.default.createElement("option", { value: 'Kiev' }, "(GMT+03:00) Kiev"),
                                react_1.default.createElement("option", { value: 'Kyiv' }, "(GMT+03:00) Kyiv"),
                                react_1.default.createElement("option", { value: 'Riga' }, "(GMT+03:00) Riga"),
                                react_1.default.createElement("option", { value: 'Sofia' }, "(GMT+03:00) Sofia"),
                                react_1.default.createElement("option", { value: 'Tallinn' }, "(GMT+03:00) Tallinn"),
                                react_1.default.createElement("option", { value: 'Vilnius' }, "(GMT+03:00) Vilnius"),
                                react_1.default.createElement("option", { value: 'Athens' }, "(GMT+03:00) Athens"),
                                react_1.default.createElement("option", { value: 'Istanbul' }, "(GMT+03:00) Istanbul"),
                                react_1.default.createElement("option", { value: 'Minsk' }, "(GMT+03:00) Minsk"),
                                react_1.default.createElement("option", { value: 'Jerusalem' }, "(GMT+03:00) Jerusalem"),
                                react_1.default.createElement("option", { value: 'Moscow' }, "(GMT+03:00) Moscow"),
                                react_1.default.createElement("option", { value: 'St. Petersburg' }, "(GMT+03:00) St. Petersburg"),
                                react_1.default.createElement("option", { value: 'Volgograd' }, "(GMT+03:00) Volgograd"),
                                react_1.default.createElement("option", { value: 'Kuwait' }, "(GMT+03:00) Kuwait"),
                                react_1.default.createElement("option", { value: 'Riyadh' }, "(GMT+03:00) Riyadh"),
                                react_1.default.createElement("option", { value: 'Nairobi' }, "(GMT+03:00) Nairobi"),
                                react_1.default.createElement("option", { value: 'Baghdad' }, "(GMT+03:00) Baghdad"),
                                react_1.default.createElement("option", { value: 'Abu Dhabi' }, "(GMT+04:00) Abu Dhabi"),
                                react_1.default.createElement("option", { value: 'Muscat' }, "(GMT+04:00) Muscat"),
                                react_1.default.createElement("option", { value: 'Baku' }, "(GMT+04:00) Baku"),
                                react_1.default.createElement("option", { value: 'Tbilisi' }, "(GMT+04:00) Tbilisi"),
                                react_1.default.createElement("option", { value: 'Yerevan' }, "(GMT+04:00) Yerevan"),
                                react_1.default.createElement("option", { value: 'Tehran' }, "(GMT+04:30) Tehran"),
                                react_1.default.createElement("option", { value: 'Kabul' }, "(GMT+04:30) Kabul"),
                                react_1.default.createElement("option", { value: 'Ekaterinburg' }, "(GMT+05:00) Ekaterinburg"),
                                react_1.default.createElement("option", { value: 'Islamabad' }, "(GMT+05:00) Islamabad"),
                                react_1.default.createElement("option", { value: 'Karachi' }, "(GMT+05:00) Karachi"),
                                react_1.default.createElement("option", { value: 'Tashkent' }, "(GMT+05:00) Tashkent"),
                                react_1.default.createElement("option", { value: 'Chennai' }, "(GMT+05:30) Chennai"),
                                react_1.default.createElement("option", { value: 'Kolkata' }, "(GMT+05:30) Kolkata"),
                                react_1.default.createElement("option", { value: 'Mumbai' }, "(GMT+05:30) Mumbai"),
                                react_1.default.createElement("option", { value: 'New Delhi' }, "(GMT+05:30) New Delhi"),
                                react_1.default.createElement("option", { value: 'Sri Jayawardenepura' }, "(GMT+05:30) Sri Jayawardenepura"),
                                react_1.default.createElement("option", { value: 'Kathmandu' }, "(GMT+05:45) Kathmandu"),
                                react_1.default.createElement("option", { value: 'Astana' }, "(GMT+06:00) Astana"),
                                react_1.default.createElement("option", { value: 'Dhaka' }, "(GMT+06:00) Dhaka"),
                                react_1.default.createElement("option", { value: 'Almaty' }, "(GMT+06:00) Almaty"),
                                react_1.default.createElement("option", { value: 'Urumqi' }, "(GMT+06:00) Urumqi"),
                                react_1.default.createElement("option", { value: 'Rangoon' }, "(GMT+06:30) Rangoon"),
                                react_1.default.createElement("option", { value: 'Novosibirsk' }, "(GMT+07:00) Novosibirsk"),
                                react_1.default.createElement("option", { value: 'Bangkok' }, "(GMT+07:00) Bangkok"),
                                react_1.default.createElement("option", { value: 'Hanoi' }, "(GMT+07:00) Hanoi"),
                                react_1.default.createElement("option", { value: 'Jakarta' }, "(GMT+07:00) Jakarta"),
                                react_1.default.createElement("option", { value: 'Krasnoyarsk' }, "(GMT+07:00) Krasnoyarsk"),
                                react_1.default.createElement("option", { value: 'Beijing' }, "(GMT+08:00) Beijing"),
                                react_1.default.createElement("option", { value: 'Chongqing' }, "(GMT+08:00) Chongqing"),
                                react_1.default.createElement("option", { value: 'Hong Kong' }, "(GMT+08:00) Hong Kong"),
                                react_1.default.createElement("option", { value: 'Kuala Lumpur' }, "(GMT+08:00) Kuala Lumpur"),
                                react_1.default.createElement("option", { value: 'Singapore' }, "(GMT+08:00) Singapore"),
                                react_1.default.createElement("option", { value: 'Taipei' }, "(GMT+08:00) Taipei"),
                                react_1.default.createElement("option", { value: 'Perth' }, "(GMT+08:00) Perth"),
                                react_1.default.createElement("option", { value: 'Irkutsk' }, "(GMT+08:00) Irkutsk"),
                                react_1.default.createElement("option", { value: 'Ulaan Bataar' }, "(GMT+08:00) Ulaan Bataar"),
                                react_1.default.createElement("option", { value: 'Seoul' }, "(GMT+09:00) Seoul"),
                                react_1.default.createElement("option", { value: 'Osaka' }, "(GMT+09:00) Osaka"),
                                react_1.default.createElement("option", { value: 'Sapporo' }, "(GMT+09:00) Sapporo"),
                                react_1.default.createElement("option", { value: 'Tokyo' }, "(GMT+09:00) Tokyo"),
                                react_1.default.createElement("option", { value: 'Yakutsk' }, "(GMT+09:00) Yakutsk"),
                                react_1.default.createElement("option", { value: 'Darwin' }, "(GMT+09:30) Darwin"),
                                react_1.default.createElement("option", { value: 'Adelaide' }, "(GMT+09:30) Adelaide"),
                                react_1.default.createElement("option", { value: 'Canberra' }, "(GMT+10:00) Canberra"),
                                react_1.default.createElement("option", { value: 'Melbourne' }, "(GMT+10:00) Melbourne"),
                                react_1.default.createElement("option", { value: 'Sydney' }, "(GMT+10:00) Sydney"),
                                react_1.default.createElement("option", { value: 'Brisbane' }, "(GMT+10:00) Brisbane"),
                                react_1.default.createElement("option", { value: 'Hobart' }, "(GMT+10:00) Hobart"),
                                react_1.default.createElement("option", { value: 'Vladivostok' }, "(GMT+10:00) Vladivostok"),
                                react_1.default.createElement("option", { value: 'Guam' }, "(GMT+10:00) Guam"),
                                react_1.default.createElement("option", { value: 'Port Moresby' }, "(GMT+10:00) Port Moresby"),
                                react_1.default.createElement("option", { value: 'Solomon Is.' }, "(GMT+10:00) Solomon Is."),
                                react_1.default.createElement("option", { value: 'Magadan' }, "(GMT+11:00) Magadan"),
                                react_1.default.createElement("option", { value: 'New Caledonia' }, "(GMT+11:00) New Caledonia"),
                                react_1.default.createElement("option", { value: 'Fiji' }, "(GMT+12:00) Fiji"),
                                react_1.default.createElement("option", { value: 'Kamchatka' }, "(GMT+12:00) Kamchatka"),
                                react_1.default.createElement("option", { value: 'Marshall Is.' }, "(GMT+12:00) Marshall Is."),
                                react_1.default.createElement("option", { value: 'Auckland' }, "(GMT+12:00) Auckland"),
                                react_1.default.createElement("option", { value: 'Wellington' }, "(GMT+12:00) Wellington"),
                                react_1.default.createElement("option", { value: "Nuku'alofa" }, "(GMT+13:00) Nuku'alofa")),
                            formik.touched.timeZone && formik.errors.timeZone && (react_1.default.createElement("div", { className: 'fv-plugins-message-container' },
                                react_1.default.createElement("div", { className: 'fv-help-block' }, formik.errors.timeZone))))),
                    react_1.default.createElement("div", { className: 'row mb-6' },
                        react_1.default.createElement("label", { className: 'col-lg-4 col-form-label required fw-bold fs-6' }, "Currency"),
                        react_1.default.createElement("div", { className: 'col-lg-8 fv-row' },
                            react_1.default.createElement("select", __assign({ className: 'form-select form-select-solid form-select-lg' }, formik.getFieldProps('currency')),
                                react_1.default.createElement("option", { value: '' }, "Select a currency.."),
                                react_1.default.createElement("option", { value: 'USD' }, "USD - USA dollar"),
                                react_1.default.createElement("option", { value: 'GBP' }, "GBP - British pound"),
                                react_1.default.createElement("option", { value: 'AUD' }, "AUD - Australian dollar"),
                                react_1.default.createElement("option", { value: 'JPY' }, "JPY - Japanese yen"),
                                react_1.default.createElement("option", { value: 'SEK' }, "SEK - Swedish krona"),
                                react_1.default.createElement("option", { value: 'CAD' }, "CAD - Canadian dollar"),
                                react_1.default.createElement("option", { value: 'CHF' }, "CHF - Swiss franc")),
                            formik.touched.currency && formik.errors.currency && (react_1.default.createElement("div", { className: 'fv-plugins-message-container' },
                                react_1.default.createElement("div", { className: 'fv-help-block' }, formik.errors.currency))))),
                    react_1.default.createElement("div", { className: 'row mb-6' },
                        react_1.default.createElement("label", { className: 'col-lg-4 col-form-label fw-bold fs-6' }, "Communication"),
                        react_1.default.createElement("div", { className: 'col-lg-8 fv-row' },
                            react_1.default.createElement("div", { className: 'd-flex align-items-center mt-3' },
                                react_1.default.createElement("label", { className: 'form-check form-check-inline form-check-solid me-5' },
                                    react_1.default.createElement("input", { className: 'form-check-input', name: 'communication[]', type: 'checkbox', defaultChecked: (_a = data.communications) === null || _a === void 0 ? void 0 : _a.email, onChange: function () {
                                            var _a, _b;
                                            updateData({
                                                communications: {
                                                    email: !((_a = data.communications) === null || _a === void 0 ? void 0 : _a.email),
                                                    phone: (_b = data.communications) === null || _b === void 0 ? void 0 : _b.phone,
                                                },
                                            });
                                        } }),
                                    react_1.default.createElement("span", { className: 'fw-bold ps-2 fs-6' }, "Email")),
                                react_1.default.createElement("label", { className: 'form-check form-check-inline form-check-solid' },
                                    react_1.default.createElement("input", { className: 'form-check-input', name: 'communication[]', type: 'checkbox', defaultChecked: (_b = data.communications) === null || _b === void 0 ? void 0 : _b.phone, onChange: function () {
                                            var _a, _b;
                                            updateData({
                                                communications: {
                                                    email: (_a = data.communications) === null || _a === void 0 ? void 0 : _a.email,
                                                    phone: !((_b = data.communications) === null || _b === void 0 ? void 0 : _b.phone),
                                                },
                                            });
                                        } }),
                                    react_1.default.createElement("span", { className: 'fw-bold ps-2 fs-6' }, "Phone"))))),
                    react_1.default.createElement("div", { className: 'row mb-0' },
                        react_1.default.createElement("label", { className: 'col-lg-4 col-form-label fw-bold fs-6' }, "Allow Marketing"),
                        react_1.default.createElement("div", { className: 'col-lg-8 d-flex align-items-center' },
                            react_1.default.createElement("div", { className: 'form-check form-check-solid form-switch fv-row' },
                                react_1.default.createElement("input", { className: 'form-check-input w-45px h-30px', type: 'checkbox', id: 'allowmarketing', defaultChecked: data.allowMarketing, onChange: function () {
                                        updateData({ allowMarketing: !data.allowMarketing });
                                    } }),
                                react_1.default.createElement("label", { className: 'form-check-label' }))))),
                react_1.default.createElement("div", { className: 'card-footer d-flex justify-content-end py-6 px-9' },
                    react_1.default.createElement("button", { type: 'submit', className: 'btn btn-primary', disabled: loading },
                        !loading && 'Save Changes',
                        loading && (react_1.default.createElement("span", { className: 'indicator-progress', style: { display: 'block' } },
                            "Please wait...",
                            ' ',
                            react_1.default.createElement("span", { className: 'spinner-border spinner-border-sm align-middle ms-2' })))))))));
};
exports.ProfileDetails = ProfileDetails;
