"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Campaigns = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var Card5_1 = require("../../../../_metronic/partials/content/cards/Card5");
function Campaigns() {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement("div", { className: 'd-flex flex-wrap flex-stack mb-6' },
            react_1.default.createElement("h3", { className: 'fw-bolder my-2' },
                "My Campaigns",
                react_1.default.createElement("span", { className: 'fs-6 text-gray-400 fw-bold ms-1' }, "30 Days")),
            react_1.default.createElement("div", { className: 'd-flex align-items-center my-2' },
                react_1.default.createElement("div", { className: 'w-100px me-5' },
                    react_1.default.createElement("select", { name: 'status', "data-control": 'select2', "data-hide-search": 'true', className: 'form-select form-select-white form-select-sm', defaultValue: '1' },
                        react_1.default.createElement("option", { value: '1' }, "30 Days"),
                        react_1.default.createElement("option", { value: '2' }, "90 Days"),
                        react_1.default.createElement("option", { value: '3' }, "6 Months"),
                        react_1.default.createElement("option", { value: '4' }, "1 Year"))),
                react_1.default.createElement("button", { className: 'btn btn-primary btn-sm', "data-bs-toggle": 'tooltip', title: 'Coming soon' }, "Add Campaign"))),
        react_1.default.createElement("div", { className: 'row g-6 g-xl-9' },
            react_1.default.createElement("div", { className: 'col-sm-6 col-xl-4' },
                react_1.default.createElement(Card5_1.Card5, { image: '/media/svg/brand-logos/twitch.svg', title: 'Twitch Posts', description: '$500.00', status: 'down', statusValue: 40.5, statusDesc: 'more impressions', progress: 0.5, progressType: 'MRR' })),
            react_1.default.createElement("div", { className: 'col-sm-6 col-xl-4' },
                react_1.default.createElement(Card5_1.Card5, { image: '/media/svg/brand-logos/twitter.svg', title: 'Twitter Followers', description: '807k', status: 'up', statusValue: 17.62, statusDesc: 'Followers growth', progress: 5, progressType: 'New trials' })),
            react_1.default.createElement("div", { className: 'col-sm-6 col-xl-4' },
                react_1.default.createElement(Card5_1.Card5, { image: '/media/svg/brand-logos/spotify.svg', title: 'Spotify Listeners', description: '1,073', status: 'down', statusValue: 10.45, statusDesc: 'Less comments than usual', progress: 40, progressType: 'Impressions' })),
            react_1.default.createElement("div", { className: 'col-sm-6 col-xl-4' },
                react_1.default.createElement(Card5_1.Card5, { image: '/media/svg/brand-logos/pinterest-p.svg', title: 'Pinterest Posts', description: '97', status: 'up', statusValue: 26.1, statusDesc: 'More posts', progress: 10, progressType: 'Spend' })),
            react_1.default.createElement("div", { className: 'col-sm-6 col-xl-4' },
                react_1.default.createElement(Card5_1.Card5, { image: '/media/svg/brand-logos/github.svg', title: 'Github Contributes', description: '4,109', status: 'down', statusValue: 32.8, statusDesc: 'Less contributions', progress: 40, progressType: 'Dispute' })),
            react_1.default.createElement("div", { className: 'col-sm-6 col-xl-4' },
                react_1.default.createElement(Card5_1.Card5, { image: '/media/svg/brand-logos/youtube-play.svg', title: 'Youtube Subscribers', description: '354', status: 'up', statusValue: 29.45, statusDesc: 'Subscribers growth', progress: 40, progressType: 'Subscribers' })),
            react_1.default.createElement("div", { className: 'col-sm-6 col-xl-4' },
                react_1.default.createElement(Card5_1.Card5, { image: '/media/svg/brand-logos/telegram.svg', title: 'Telegram Posts', description: '566', status: 'up', statusValue: 11.4, statusDesc: 'more clicks', progress: 40, progressType: 'Profit' })),
            react_1.default.createElement("div", { className: 'col-sm-6 col-xl-4' },
                react_1.default.createElement(Card5_1.Card5, { image: '/media/svg/brand-logos/reddit.svg', title: 'Reddit Awards', description: '2.1M', status: 'up', statusValue: 46.7, statusDesc: 'more adds', progress: 0.0, progressType: 'Retention' }))),
        react_1.default.createElement("div", { className: 'd-flex flex-stack flex-wrap pt-10' },
            react_1.default.createElement("div", { className: 'fs-6 fw-bold text-gray-700' }, "Showing 1 to 10 of 50 entries"),
            react_1.default.createElement("ul", { className: 'pagination' },
                react_1.default.createElement("li", { className: 'page-item previous' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' },
                        react_1.default.createElement("i", { className: 'previous' }))),
                react_1.default.createElement("li", { className: 'page-item active' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "1")),
                react_1.default.createElement("li", { className: 'page-item' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "2")),
                react_1.default.createElement("li", { className: 'page-item' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "3")),
                react_1.default.createElement("li", { className: 'page-item' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "4")),
                react_1.default.createElement("li", { className: 'page-item' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "5")),
                react_1.default.createElement("li", { className: 'page-item' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "6")),
                react_1.default.createElement("li", { className: 'page-item next' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' },
                        react_1.default.createElement("i", { className: 'next' })))))));
}
exports.Campaigns = Campaigns;
