"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Connections = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var Card3_1 = require("../../../../_metronic/partials/content/cards/Card3");
function Connections() {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement("div", { className: 'd-flex flex-wrap flex-stack mb-6' },
            react_1.default.createElement("h3", { className: 'fw-bolder my-2' },
                "My Contacts",
                react_1.default.createElement("span", { className: 'fs-6 text-gray-400 fw-bold ms-1' }, "(59)")),
            react_1.default.createElement("div", { className: 'd-flex my-2' },
                react_1.default.createElement("select", { name: 'status', "data-control": 'select2', "data-hide-search": 'true', className: 'form-select form-select-white form-select-sm w-125px', defaultValue: 'Online' },
                    react_1.default.createElement("option", { value: 'Online' }, "Online"),
                    react_1.default.createElement("option", { value: 'Pending' }, "Pending"),
                    react_1.default.createElement("option", { value: 'Declined' }, "Declined"),
                    react_1.default.createElement("option", { value: 'Accepted' }, "Accepted")))),
        react_1.default.createElement("div", { className: 'row g-6 g-xl-9' },
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { avatar: '/media/avatars/150-1.jpg', name: 'Emma Smith', job: 'Art Director', avgEarnings: '$14,560', totalEarnings: '$236,400' })),
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { color: 'danger', name: 'Melody Macy', job: 'Marketing Analytic', avgEarnings: '$14,560', totalEarnings: '$236,400', online: true })),
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { avatar: '/media/avatars/150-2.jpg', name: 'Max Smith', job: 'Software Enginer', avgEarnings: '$14,560', totalEarnings: '$236,400' })),
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { avatar: '/media/avatars/150-4.jpg', name: 'Sean Bean', job: 'Web Developer', avgEarnings: '$14,560', totalEarnings: '$236,400' })),
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { avatar: '/media/avatars/150-15.jpg', name: 'Brian Cox', job: 'UI/UX Designer', avgEarnings: '$14,560', totalEarnings: '$236,400' })),
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { color: 'warning', name: 'Mikaela Collins', job: 'Head Of Marketing', avgEarnings: '$14,560', totalEarnings: '$236,400', online: true })),
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { avatar: '/media/avatars/150-8.jpg', name: 'Francis Mitcham', job: 'Software Arcitect', avgEarnings: '$14,560', totalEarnings: '$236,400' })),
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { color: 'danger', name: 'Olivia Wild', job: 'System Admin', avgEarnings: '$14,560', totalEarnings: '$236,400', online: true })),
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { color: 'primary', name: 'Neil Owen', job: 'Account Manager', avgEarnings: '$14,560', totalEarnings: '$236,400', online: true })),
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { avatar: '/media/avatars/150-6.jpg', name: 'Dan Wilson', job: 'Web Desinger', avgEarnings: '$14,560', totalEarnings: '$236,400' })),
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { color: 'danger', name: 'Emma Bold', job: 'Corporate Finance', avgEarnings: '$14,560', totalEarnings: '$236,400', online: true })),
            react_1.default.createElement("div", { className: 'col-md-6 col-xxl-4' },
                react_1.default.createElement(Card3_1.Card3, { avatar: '/media/avatars/150-7.jpg', name: 'Ana Crown', job: 'Customer Relationship', avgEarnings: '$14,560', totalEarnings: '$236,400' }))),
        react_1.default.createElement("div", { className: 'd-flex flex-stack flex-wrap pt-10' },
            react_1.default.createElement("div", { className: 'fs-6 fw-bold text-gray-700' }, "Showing 1 to 10 of 50 entries"),
            react_1.default.createElement("ul", { className: 'pagination' },
                react_1.default.createElement("li", { className: 'page-item previous' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' },
                        react_1.default.createElement("i", { className: 'previous' }))),
                react_1.default.createElement("li", { className: 'page-item active' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "1")),
                react_1.default.createElement("li", { className: 'page-item' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "2")),
                react_1.default.createElement("li", { className: 'page-item' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "3")),
                react_1.default.createElement("li", { className: 'page-item' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "4")),
                react_1.default.createElement("li", { className: 'page-item' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "5")),
                react_1.default.createElement("li", { className: 'page-item' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' }, "6")),
                react_1.default.createElement("li", { className: 'page-item next' },
                    react_1.default.createElement("a", { href: '#', className: 'page-link' },
                        react_1.default.createElement("i", { className: 'next' })))))));
}
exports.Connections = Connections;
