"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MenuTestPage = void 0;
var react_inlinesvg_1 = require("react-inlinesvg");
var helpers_1 = require("../../_metronic/helpers");
var MenuTestPage = function () {
    return (React.createElement("div", { className: 'row' },
        React.createElement("div", { className: 'card card-custom' },
            React.createElement("div", { className: 'card-body p-9' },
                React.createElement("div", { className: 'd-flex align-items-stretch mb-20' },
                    React.createElement("div", { className: 'header-menu align-items-stretch', "data-kt-drawer": 'true', "data-kt-drawer-name": 'header-menu', "data-kt-drawer-activate": '{default: true, lg: false}', "data-kt-drawer-overlay": 'true', "data-kt-drawer-width": "{default:'200px', '300px': '250px'}", "data-kt-drawer-direction": 'start', "data-kt-drawer-toggle": '#kt_header_menu_toggle' },
                        React.createElement("div", { className: 'menu menu-lg-rounded menu-column menu-lg-row menu-state-bg menu-title-gray-700 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-400 fw-bold my-5 my-lg-0 align-items-stretch', id: '#kt_header_menu', "data-kt-menu": 'true' },
                            React.createElement("div", { className: 'menu-item me-lg-2' },
                                React.createElement("a", { className: 'menu-link active py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=index' },
                                    React.createElement("span", { className: 'menu-title' }, "Dashboard"))),
                            React.createElement("div", { "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'bottom-start', className: 'menu-item me-lg-2' },
                                React.createElement("span", { className: 'menu-link py-3' },
                                    React.createElement("span", { className: 'menu-title' }, "Pages"),
                                    React.createElement("span", { className: 'menu-arrow d-lg-none' })),
                                React.createElement("div", { className: 'menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown menu-rounded-0 py-lg-4 w-100 w-lg-225px', style: { margin: '0px' } },
                                    React.createElement("div", { "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'right-start', className: 'menu-item' },
                                        React.createElement("span", { className: 'menu-link py-3' },
                                            React.createElement("span", { className: 'menu-icon' },
                                                React.createElement("span", { className: 'svg-icon' },
                                                    React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                            React.createElement("span", { className: 'menu-title' }, "Profile"),
                                            React.createElement("span", { className: 'menu-arrow' })),
                                        React.createElement("div", { className: 'menu-sub menu-sub-accordion menu-sub-lg-dropdown menu-active-bg py-4 w-100 w-lg-225px', style: { margin: '0px' } },
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("span", { className: 'menu-link py-3' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Overview"))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/projects' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Projects"))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/campaigns' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Campaigns"))),
                                            React.createElement("div", { "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'right-start', className: 'menu-item' },
                                                React.createElement("span", { className: 'menu-link py-3' },
                                                    React.createElement("span", { className: 'menu-icon' },
                                                        React.createElement("span", { className: 'svg-icon' },
                                                            React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                                    React.createElement("span", { className: 'menu-title' }, "Profile -"),
                                                    React.createElement("span", { className: 'menu-arrow' })),
                                                React.createElement("div", { className: 'menu-sub menu-sub-accordion menu-sub-lg-dropdown menu-active-bg py-4 w-100 w-lg-225px' },
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/overview' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Overview"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/projects' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Projects"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/campaigns' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Campaigns"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/documents' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Documents"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/followers' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Followers"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/activity' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Activity"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/dashboard' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Dashboard"))))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/documents' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Documents"))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/followers' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Followers"))),
                                            React.createElement("div", { "data-kt-menu-trigger": 'hover', "data-kt-menu-placement": 'right-start', className: 'menu-item' },
                                                React.createElement("span", { className: 'menu-link py-3' },
                                                    React.createElement("span", { className: 'menu-icon' },
                                                        React.createElement("span", { className: 'svg-icon' },
                                                            React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                                    React.createElement("span", { className: 'menu-title' }, "Profile -"),
                                                    React.createElement("span", { className: 'menu-arrow' })),
                                                React.createElement("div", { className: 'menu-sub menu-sub-accordion menu-sub-lg-dropdown menu-active-bg py-4 w-100 w-lg-225px' },
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/overview' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Overview"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/projects' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Projects"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/campaigns' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Campaigns"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/documents' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Documents"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/followers' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Followers"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/activity' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Activity"))),
                                                    React.createElement("div", { className: 'menu-item' },
                                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/dashboard' },
                                                            React.createElement("span", { className: 'menu-bullet' },
                                                                React.createElement("span", { className: 'bullet bullet-dot' })),
                                                            React.createElement("span", { className: 'menu-title' }, "Dashboard"))))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/activity' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Activity"))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/dashboard' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Dashboard"))))),
                                    React.createElement("div", { "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'right-start', className: 'menu-item' },
                                        React.createElement("span", { className: 'menu-link py-3' },
                                            React.createElement("span", { className: 'menu-icon' },
                                                React.createElement("span", { className: 'svg-icon' },
                                                    React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                            React.createElement("span", { className: 'menu-title' }, "Projects"),
                                            React.createElement("span", { className: 'menu-arrow' })),
                                        React.createElement("div", { className: 'menu-sub menu-sub-accordion menu-sub-lg-dropdown py-4 w-100 w-lg-225px' },
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/overview' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Overview"))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/lists' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Lists"))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/activity' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Activity"))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/files' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Files"))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/users' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Users"))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/targets' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Targets"))))),
                                    React.createElement("div", { "data-kt-menu-trigger": 'click', className: 'menu-item' },
                                        React.createElement("span", { className: 'menu-link py-3' },
                                            React.createElement("span", { className: 'menu-icon' },
                                                React.createElement("span", { className: 'svg-icon' },
                                                    React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                            React.createElement("span", { className: 'menu-title' }, "Wizards"),
                                            React.createElement("span", { className: 'menu-arrow' })),
                                        React.createElement("div", { className: 'menu-sub menu-sub-accordion' },
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/wizards/wizard-vertical' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Wizard Vertical"))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/wizards/wizard-horizontal' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Wizard Horizontal"))))),
                                    React.createElement("div", { "data-kt-menu-trigger": 'click', className: 'menu-item' },
                                        React.createElement("span", { className: 'menu-link py-3' },
                                            React.createElement("span", { className: 'menu-icon' },
                                                React.createElement("span", { className: 'svg-icon' },
                                                    React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                            React.createElement("span", { className: 'menu-title' }, "Search"),
                                            React.createElement("span", { className: 'menu-arrow' })),
                                        React.createElement("div", { className: 'menu-sub menu-sub-accordion' },
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/search/search-horizontal' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Search Horizontal"))),
                                            React.createElement("div", { className: 'menu-item' },
                                                React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/search/search-vertical' },
                                                    React.createElement("span", { className: 'menu-bullet' },
                                                        React.createElement("span", { className: 'bullet bullet-dot' })),
                                                    React.createElement("span", { className: 'menu-title' }, "Search Vertical"))))))),
                            React.createElement("div", { "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'bottom-start', className: 'menu-item me-lg-2' },
                                React.createElement("span", { className: 'menu-link py-3' },
                                    React.createElement("span", { className: 'menu-title' }, "Resources"),
                                    React.createElement("span", { className: 'menu-arrow d-lg-none' })),
                                React.createElement("div", { className: 'menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown menu-rounded-0 py-lg-4 w-100 w-lg-225px', style: { margin: '0px' } },
                                    React.createElement("div", { className: 'menu-item' },
                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=documentation/getting-started' },
                                            React.createElement("span", { className: 'menu-icon' },
                                                React.createElement("span", { className: 'svg-icon svg-icon-1' },
                                                    React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                            React.createElement("span", { className: 'menu-title' }, "Documentation"))),
                                    React.createElement("div", { className: 'menu-item' },
                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=layout-builder' },
                                            React.createElement("span", { className: 'menu-icon' },
                                                React.createElement("span", { className: 'svg-icon svg-icon-1' },
                                                    React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                            React.createElement("span", { className: 'menu-title' }, "Layout Builder"))),
                                    React.createElement("div", { className: 'menu-item' },
                                        React.createElement("a", { className: 'menu-link py-3', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=documentation/getting-started/changelog' },
                                            React.createElement("span", { className: 'menu-icon' },
                                                React.createElement("span", { className: 'svg-icon svg-icon-1' },
                                                    React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                            React.createElement("span", { className: 'menu-title' }, "Changelog"))))),
                            React.createElement("div", { "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'bottom-start', className: 'menu-item me-lg-2' },
                                React.createElement("span", { className: 'menu-link py-3' },
                                    React.createElement("span", { className: 'menu-title' }, "Mega Menu"),
                                    React.createElement("span", { className: 'menu-arrow d-lg-none' })),
                                React.createElement("div", { className: 'menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown w-100 w-lg-600px p-5 p-lg-5', style: { margin: '0px' } },
                                    React.createElement("div", { className: 'row', "data-kt-menu-dismiss": 'true' },
                                        React.createElement("div", { className: 'col-lg-4 border-left-lg-1' },
                                            React.createElement("div", { className: 'menu-inline menu-column menu-active-bg' },
                                                React.createElement("div", { className: 'menu-item' },
                                                    React.createElement("a", { href: '#', className: 'menu-link' },
                                                        React.createElement("span", { className: 'menu-bullet' },
                                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                                        React.createElement("span", { className: 'menu-title' }, "Example link"))),
                                                React.createElement("div", { className: 'menu-item' },
                                                    React.createElement("a", { href: '#', className: 'menu-link' },
                                                        React.createElement("span", { className: 'menu-bullet' },
                                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                                        React.createElement("span", { className: 'menu-title' }, "Example link"))),
                                                React.createElement("div", { className: 'menu-item' },
                                                    React.createElement("a", { href: '#', className: 'menu-link' },
                                                        React.createElement("span", { className: 'menu-bullet' },
                                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                                        React.createElement("span", { className: 'menu-title' }, "Example link"))),
                                                React.createElement("div", { className: 'menu-item' },
                                                    React.createElement("a", { href: '#', className: 'menu-link' },
                                                        React.createElement("span", { className: 'menu-bullet' },
                                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                                        React.createElement("span", { className: 'menu-title' }, "Example link"))),
                                                React.createElement("div", { className: 'menu-item' },
                                                    React.createElement("a", { href: '#', className: 'menu-link' },
                                                        React.createElement("span", { className: 'menu-bullet' },
                                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                                        React.createElement("span", { className: 'menu-title' }, "Example link"))))),
                                        React.createElement("div", { className: 'col-lg-4' },
                                            React.createElement("div", { className: 'menu-inline menu-column menu-active-bg' },
                                                React.createElement("div", { className: 'menu-item' },
                                                    React.createElement("a", { href: '#', className: 'menu-link' },
                                                        React.createElement("span", { className: 'menu-bullet' },
                                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                                        React.createElement("span", { className: 'menu-title' }, "Example link"))),
                                                React.createElement("div", { className: 'menu-item' },
                                                    React.createElement("a", { href: '#', className: 'menu-link' },
                                                        React.createElement("span", { className: 'menu-bullet' },
                                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                                        React.createElement("span", { className: 'menu-title' }, "Example link"))),
                                                React.createElement("div", { className: 'menu-item' },
                                                    React.createElement("a", { href: '#', className: 'menu-link' },
                                                        React.createElement("span", { className: 'menu-bullet' },
                                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                                        React.createElement("span", { className: 'menu-title' }, "Example link"))),
                                                React.createElement("div", { className: 'menu-item' },
                                                    React.createElement("a", { href: '#', className: 'menu-link' },
                                                        React.createElement("span", { className: 'menu-bullet' },
                                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                                        React.createElement("span", { className: 'menu-title' }, "Example link"))),
                                                React.createElement("div", { className: 'menu-item' },
                                                    React.createElement("a", { href: '#', className: 'menu-link' },
                                                        React.createElement("span", { className: 'menu-bullet' },
                                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                                        React.createElement("span", { className: 'menu-title' }, "Example link"))))),
                                        React.createElement("div", { className: 'col-lg-4' }, "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English."))))))),
                React.createElement("div", { className: 'mb-20 w-200px' },
                    React.createElement("div", { className: 'd-flex align-items-center ms-1 ms-lg-3', "data-kt-menu-target": '#kt_header_search_menu', "data-kt-menu-trigger": 'click', "data-kt-menu-permanent": 'true', "data-kt-menu-placement": 'bottom-start' },
                        React.createElement("div", { className: 'btn btn-icon btn-active-light-primary w-30px h-30px w-lg-40px h-lg-40px' },
                            React.createElement("span", { className: 'svg-icon svg-icon-2 svg-icon-lg-1' },
                                React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') })))),
                    React.createElement("div", { className: 'menu menu-sub menu-sub-dropdown w-250px w-lg-300px px-7 py-5', "data-kt-menu": 'true', id: 'kt_header_search_menu', style: { margin: '0px' } },
                        React.createElement("div", { id: 'kt_header_search', "data-kt-search-keypress": 'true', "data-kt-search-min-length": '3', "data-kt-search-enter": 'enter', "data-kt-search-mode": 'inline', "data-kt-search-input-focus": 'true', "data-kt-search-trigger": '#kt_header_search_trigger', "data-kt-search-input": '#kt_header_search_input', "data-kt-search-spinner": '#kt_header_search_spinner', "data-kt-search-clear": '#kt_header_search_clear', "data-kt-search-results": '#kt_header_search_results', "data-kt-search-suggestions": '#kt_header_search_suggestions', "data-kt-search-empty": '#kt_header_search_empty' },
                            React.createElement("div", { className: 'position-relative' },
                                React.createElement("span", { className: 'svg-icon svg-icon-1 svg-icon-gray-500 position-absolute top-50 translate-middle-y ms-0' },
                                    React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') })),
                                React.createElement("input", { type: 'text', className: 'form-control form-control-flush ps-10', name: 'search', value: '', placeholder: 'Search...', id: 'kt_header_search_input', onChange: function () { } }),
                                React.createElement("span", { className: 'position-absolute top-50 end-0 translate-middle-y lh-0 d-none me-1', id: 'kt_header_search_spinner' },
                                    React.createElement("span", { className: 'spinner-border h-15px w-15px align-middle text-gray-400' })),
                                React.createElement("span", { className: 'btn btn-flush btn-active-color-primary position-absolute top-50 end-0 translate-middle-y lh-0 d-none', id: 'kt_header_search_clear' },
                                    React.createElement("span", { className: 'svg-icon svg-icon-1 me-0' },
                                        React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') })))),
                            React.createElement("div", { id: 'kt_header_search_results', className: 'd-none' }),
                            React.createElement("div", { id: 'kt_header_search_suggestions' }, "Suggestions"),
                            React.createElement("div", { id: 'kt_header_search_empty', className: 'd-none' }, "Sorry, no results found")))),
                React.createElement("div", { className: 'w-250px bg-light rounded py-5' },
                    React.createElement("div", { className: 'menu menu-column menu-title-gray-700 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-500', id: '#kt_aside_menu', "data-kt-menu": 'true' },
                        React.createElement("div", { className: 'menu-item' },
                            React.createElement("a", { className: 'menu-link active', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=index' },
                                React.createElement("span", { className: 'menu-icon' },
                                    React.createElement("span", { className: 'svg-icon svg-icon-1' },
                                        React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                React.createElement("span", { className: 'menu-title' }, "Dashboard"))),
                        React.createElement("div", { className: 'menu-item pt-5' },
                            React.createElement("div", { className: 'menu-content' },
                                React.createElement("span", { className: 'menu-section text-muted text-uppercase fs-8' }, "Custom"))),
                        React.createElement("div", { "data-kt-menu-trigger": 'click', className: 'menu-item' },
                            React.createElement("span", { className: 'menu-link' },
                                React.createElement("span", { className: 'menu-icon' },
                                    React.createElement("span", { className: 'svg-icon svg-icon-1' },
                                        React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                React.createElement("span", { className: 'menu-title' }, "Pages"),
                                React.createElement("span", { className: 'menu-arrow' })),
                            React.createElement("div", { className: 'menu-sub menu-sub-accordion menu-active-bg' },
                                React.createElement("div", { "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'right-start', "data-kt-menu-overflow": 'true', className: 'menu-item' },
                                    React.createElement("span", { className: 'menu-link' },
                                        React.createElement("span", { className: 'menu-bullet' },
                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                        React.createElement("span", { className: 'menu-title' }, "Profile"),
                                        React.createElement("span", { className: 'menu-arrow' })),
                                    React.createElement("div", { className: 'menu-sub menu-sub-dropdown w-200px menu-active-bg menu-title-gray-700 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-500' },
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/overview' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Overview"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/projects' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Projects"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/campaigns' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Campaigns"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/documents' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Documents"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/followers' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Followers"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/activity' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Activity"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/profile/dashboard' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Dashboard"))))),
                                React.createElement("div", { "data-kt-menu-trigger": 'click', className: 'menu-item' },
                                    React.createElement("span", { className: 'menu-link' },
                                        React.createElement("span", { className: 'menu-bullet' },
                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                        React.createElement("span", { className: 'menu-title' }, "Projects"),
                                        React.createElement("span", { className: 'menu-arrow' })),
                                    React.createElement("div", { className: 'menu-sub menu-sub-accordion menu-active-bg' },
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/overview' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Overview"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/lists' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Lists"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/activity' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Activity"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/files' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Files"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/users' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Users"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/projects/targets' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Targets"))))),
                                React.createElement("div", { "data-kt-menu-trigger": 'click', className: 'menu-item' },
                                    React.createElement("span", { className: 'menu-link' },
                                        React.createElement("span", { className: 'menu-bullet' },
                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                        React.createElement("span", { className: 'menu-title' }, "Wizards"),
                                        React.createElement("span", { className: 'menu-arrow' })),
                                    React.createElement("div", { className: 'menu-sub menu-sub-accordion menu-active-bg' },
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/wizards/wizard-vertical' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Wizard Vertical"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/wizards/wizard-horizontal' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Wizard Horizontal"))))),
                                React.createElement("div", { "data-kt-menu-trigger": 'click', className: 'menu-item' },
                                    React.createElement("span", { className: 'menu-link' },
                                        React.createElement("span", { className: 'menu-bullet' },
                                            React.createElement("span", { className: 'bullet bullet-dot' })),
                                        React.createElement("span", { className: 'menu-title' }, "Search"),
                                        React.createElement("span", { className: 'menu-arrow' })),
                                    React.createElement("div", { className: 'menu-sub menu-sub-accordion menu-active-bg' },
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/search/search-horizontal' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Search Horizontal"))),
                                        React.createElement("div", { className: 'menu-item' },
                                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=pages/search/search-vertical' },
                                                React.createElement("span", { className: 'menu-bullet' },
                                                    React.createElement("span", { className: 'bullet bullet-dot' })),
                                                React.createElement("span", { className: 'menu-title' }, "Search Vertical"))))))),
                        React.createElement("div", { className: 'menu-item' },
                            React.createElement("div", { className: 'menu-content' },
                                React.createElement("div", { className: 'separator mx-1 my-4 opacity-10' }))),
                        React.createElement("div", { className: 'menu-item' },
                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=documentation/getting-started' },
                                React.createElement("span", { className: 'menu-icon' },
                                    React.createElement("span", { className: 'svg-icon svg-icon-1' },
                                        React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                React.createElement("span", { className: 'menu-title' }, "Documentation"))),
                        React.createElement("div", { className: 'menu-item' },
                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=layout-builder' },
                                React.createElement("span", { className: 'menu-icon' },
                                    React.createElement("span", { className: 'svg-icon svg-icon-1' },
                                        React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') })),
                                    ' '),
                                React.createElement("span", { className: 'menu-title' }, "Layout Builder"))),
                        React.createElement("div", { className: 'menu-item' },
                            React.createElement("a", { className: 'menu-link', href: '/keenthemes/products/themes/start/html/demo1/dist/?page=documentation/getting-started/changelog' },
                                React.createElement("span", { className: 'menu-icon' },
                                    React.createElement("span", { className: 'svg-icon svg-icon-1' },
                                        React.createElement(react_inlinesvg_1.default, { src: (0, helpers_1.toAbsoluteUrl)('/media/logos/logo-compact.svg') }))),
                                React.createElement("span", { className: 'menu-title' }, "Changelog")))))))));
};
exports.MenuTestPage = MenuTestPage;
