"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Search = void 0;
var react_1 = require("react");
var components_1 = require("../../../assets/ts/components");
var helpers_1 = require("../../../helpers");
var Search = function () {
    var _a = (0, react_1.useState)("main"), menuState = _a[0], setMenuState = _a[1];
    var element = (0, react_1.useRef)(null);
    var wrapperElement = (0, react_1.useRef)(null);
    var resultsElement = (0, react_1.useRef)(null);
    var suggestionsElement = (0, react_1.useRef)(null);
    var emptyElement = (0, react_1.useRef)(null);
    var processs = function (search) {
        setTimeout(function () {
            var number = Math.floor(Math.random() * 6) + 1;
            // Hide recently viewed
            suggestionsElement.current.classList.add('d-none');
            if (number === 3) {
                // Hide results
                resultsElement.current.classList.add('d-none');
                // Show empty message
                emptyElement.current.classList.remove('d-none');
            }
            else {
                // Show results
                resultsElement.current.classList.remove('d-none');
                // Hide empty message
                emptyElement.current.classList.add('d-none');
            }
            // Complete search
            search.complete();
        }, 1500);
    };
    var clear = function (search) {
        // Show recently viewed
        suggestionsElement.current.classList.remove('d-none');
        // Hide results
        resultsElement.current.classList.add('d-none');
        // Hide empty message
        emptyElement.current.classList.add('d-none');
    };
    (0, react_1.useEffect)(function () {
        // Initialize search handler
        var searchObject = components_1.SearchComponent.createInsance('#kt_header_search');
        // Search handler
        searchObject.on('kt.search.process', processs);
        // Clear handler
        searchObject.on('kt.search.clear', clear);
    }, []);
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement("div", { id: 'kt_header_search', className: 'd-flex align-items-stretch', "data-kt-search-keypress": 'true', "data-kt-search-min-length": '2', "data-kt-search-enter": 'enter', "data-kt-search-layout": 'menu', "data-kt-menu-trigger": 'auto', "data-kt-menu-overflow": 'false', "data-kt-menu-permanent": 'true', "data-kt-menu-placement": 'bottom-end', ref: element },
            react_1.default.createElement("div", { className: 'd-flex align-items-center', "data-kt-search-element": 'toggle', id: 'kt_header_search_toggle' },
                react_1.default.createElement("div", { className: 'btn btn-icon btn-active-light-primary w-30px h-30px w-md-40px h-md-40px' },
                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen021.svg', className: 'svg-icon-1' }))),
            react_1.default.createElement("div", { "data-kt-search-element": 'content', className: 'menu menu-sub menu-sub-dropdown p-7 w-325px w-md-375px' },
                react_1.default.createElement("div", { className: "".concat(menuState === 'main' ? '' : 'd-none'), ref: wrapperElement, "data-kt-search-element": 'wrapper' },
                    react_1.default.createElement("form", { "data-kt-search-element": 'form', className: 'w-100 position-relative mb-3', autoComplete: 'off' },
                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen021.svg', className: 'svg-icon-2 svg-icon-lg-1 svg-icon-gray-500 position-absolute top-50 translate-middle-y ms-0' }),
                        react_1.default.createElement("input", { type: 'text', className: 'form-control form-control-flush ps-10', name: 'search', placeholder: 'Search...', "data-kt-search-element": 'input' }),
                        react_1.default.createElement("span", { className: 'position-absolute top-50 end-0 translate-middle-y lh-0 d-none me-1', "data-kt-search-element": 'spinner' },
                            react_1.default.createElement("span", { className: 'spinner-border h-15px w-15px align-middle text-gray-400' })),
                        react_1.default.createElement("span", { className: 'btn btn-flush btn-active-color-primary position-absolute top-50 end-0 translate-middle-y lh-0 d-none', "data-kt-search-element": 'clear' },
                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr061.svg', className: 'svg-icon-2 svg-icon-lg-1 me-0' })),
                        react_1.default.createElement("div", { className: 'position-absolute top-50 end-0 translate-middle-y', "data-kt-search-element": 'toolbar' },
                            react_1.default.createElement("div", { "data-kt-search-element": 'preferences-show', className: 'btn btn-icon w-20px btn-sm btn-active-color-primary me-1', "data-bs-toggle": 'tooltip', onClick: function () { setMenuState("preferences"); }, title: 'Show search preferences' },
                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/coding/cod001.svg', className: 'svg-icon-1' })),
                            react_1.default.createElement("div", { "data-kt-search-element": 'advanced-options-form-show', className: 'btn btn-icon w-20px btn-sm btn-active-color-primary', "data-bs-toggle": 'tooltip', onClick: function () { setMenuState("advanced"); }, title: 'Show more search options' },
                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr072.svg', className: 'svg-icon-2' })))),
                    react_1.default.createElement("div", { ref: resultsElement, "data-kt-search-element": 'results', className: 'd-none' },
                        react_1.default.createElement("div", { className: 'scroll-y mh-200px mh-lg-350px' },
                            react_1.default.createElement("h3", { className: 'fs-5 text-muted m-0 pb-5', "data-kt-search-element": 'category-title' }, "Users"),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-1.jpg'), alt: '' })),
                                react_1.default.createElement("div", { className: 'd-flex flex-column justify-content-start fw-bold' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Karina Clark"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "Marketing Manager"))),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-3.jpg'), alt: '' })),
                                react_1.default.createElement("div", { className: 'd-flex flex-column justify-content-start fw-bold' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Olivia Bold"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "Software Engineer"))),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-8.jpg'), alt: '' })),
                                react_1.default.createElement("div", { className: 'd-flex flex-column justify-content-start fw-bold' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Ana Clark"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "UI/UX Designer"))),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-11.jpg'), alt: '' })),
                                react_1.default.createElement("div", { className: 'd-flex flex-column justify-content-start fw-bold' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Nick Pitola"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "Art Director"))),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/avatars/150-12.jpg'), alt: '' })),
                                react_1.default.createElement("div", { className: 'd-flex flex-column justify-content-start fw-bold' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Edward Kulnic"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "System Administrator"))),
                            react_1.default.createElement("h3", { className: 'fs-5 text-muted m-0 pt-5 pb-5', "data-kt-search-element": 'category-title' }, "Customers"),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement("img", { className: 'w-20px h-20px', src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/volicity-9.svg'), alt: '' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column justify-content-start fw-bold' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Company Rbranding"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "UI Design"))),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement("img", { className: 'w-20px h-20px', src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/tvit.svg'), alt: '' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column justify-content-start fw-bold' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Company Re-branding"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "Web Development"))),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement("img", { className: 'w-20px h-20px', src: (0, helpers_1.toAbsoluteUrl)('/media/svg/misc/infography.svg'), alt: '' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column justify-content-start fw-bold' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Business Analytics App"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "Administration"))),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement("img", { className: 'w-20px h-20px', src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/leaf.svg'), alt: '' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column justify-content-start fw-bold' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "EcoLeaf App Launch"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "Marketing"))),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement("img", { className: 'w-20px h-20px', src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/tower.svg'), alt: '' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column justify-content-start fw-bold' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Tower Group Website"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "Google Adwords"))),
                            react_1.default.createElement("h3", { className: 'fs-5 text-muted m-0 pt-5 pb-5', "data-kt-search-element": 'category-title' }, "Projects"),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen005.svg', className: 'svg-icon-2 svg-icon-primary' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Si-Fi Project by AU Themes"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "#45670"))),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen032.svg', className: 'svg-icon-2 svg-icon-primary' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Shopix Mobile App Planning"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "#45690"))),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/communication/com012.svg', className: 'svg-icon-2 svg-icon-primary' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Finance Monitoring SAAS Discussion"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "#21090"))),
                            react_1.default.createElement("a", { href: '/#', className: 'd-flex text-dark text-hover-primary align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/communication/com006.svg', className: 'svg-icon-2 svg-icon-primary' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column' },
                                    react_1.default.createElement("span", { className: 'fs-6 fw-bold' }, "Dashboard Analitics Launch"),
                                    react_1.default.createElement("span", { className: 'fs-7 fw-bold text-muted' }, "#34560"))))),
                    react_1.default.createElement("div", { ref: suggestionsElement, className: 'mb-4', "data-kt-search-element": 'main' },
                        react_1.default.createElement("div", { className: 'd-flex flex-stack fw-bold mb-4' },
                            react_1.default.createElement("span", { className: 'text-muted fs-6 me-2' }, "Recently Searched:")),
                        react_1.default.createElement("div", { className: 'scroll-y mh-200px mh-lg-325px' },
                            react_1.default.createElement("div", { className: 'd-flex align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/electronics/elc004.svg', className: 'svg-icon-2 svg-icon-primary' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column' },
                                    react_1.default.createElement("a", { href: '/#', className: 'fs-6 text-gray-800 text-hover-primary fw-bold' }, "BoomApp by Keenthemes"),
                                    react_1.default.createElement("span", { className: 'fs-7 text-muted fw-bold' }, "#45789"))),
                            react_1.default.createElement("div", { className: 'd-flex align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/graphs/gra001.svg', className: 'svg-icon-2 svg-icon-primary' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column' },
                                    react_1.default.createElement("a", { href: '/#', className: 'fs-6 text-gray-800 text-hover-primary fw-bold' }, "\"Kept API Project Meeting"),
                                    react_1.default.createElement("span", { className: 'fs-7 text-muted fw-bold' }, "#84050"))),
                            react_1.default.createElement("div", { className: 'd-flex align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/graphs/gra006.svg', className: 'svg-icon-2 svg-icon-primary' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column' },
                                    react_1.default.createElement("a", { href: '/#', className: 'fs-6 text-gray-800 text-hover-primary fw-bold' }, "\"KPI Monitoring App Launch"),
                                    react_1.default.createElement("span", { className: 'fs-7 text-muted fw-bold' }, "#84250"))),
                            react_1.default.createElement("div", { className: 'd-flex align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/graphs/gra002.svg', className: 'svg-icon-2 svg-icon-primary' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column' },
                                    react_1.default.createElement("a", { href: '/#', className: 'fs-6 text-gray-800 text-hover-primary fw-bold' }, "Project Reference FAQ"),
                                    react_1.default.createElement("span", { className: 'fs-7 text-muted fw-bold' }, "#67945"))),
                            react_1.default.createElement("div", { className: 'd-flex align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/communication/com010.svg', className: 'svg-icon-2 svg-icon-primary' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column' },
                                    react_1.default.createElement("a", { href: '/#', className: 'fs-6 text-gray-800 text-hover-primary fw-bold' }, "\"FitPro App Development"),
                                    react_1.default.createElement("span", { className: 'fs-7 text-muted fw-bold' }, "#84250"))),
                            react_1.default.createElement("div", { className: 'd-flex align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/finance/fin001.svg', className: 'svg-icon-2 svg-icon-primary' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column' },
                                    react_1.default.createElement("a", { href: '/#', className: 'fs-6 text-gray-800 text-hover-primary fw-bold' }, "Shopix Mobile App"),
                                    react_1.default.createElement("span", { className: 'fs-7 text-muted fw-bold' }, "#45690"))),
                            react_1.default.createElement("div", { className: 'd-flex align-items-center mb-5' },
                                react_1.default.createElement("div", { className: 'symbol symbol-40px me-4' },
                                    react_1.default.createElement("span", { className: 'symbol-label bg-light' },
                                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/graphs/gra002.svg', className: 'svg-icon-2 svg-icon-primary' }))),
                                react_1.default.createElement("div", { className: 'd-flex flex-column' },
                                    react_1.default.createElement("a", { href: '/#', className: 'fs-6 text-gray-800 text-hover-primary fw-bold' }, "\"Landing UI Design\" Launch"),
                                    react_1.default.createElement("span", { className: 'fs-7 text-muted fw-bold' }, "#24005"))))),
                    react_1.default.createElement("div", { ref: emptyElement, "data-kt-search-element": 'empty', className: 'text-center d-none' },
                        react_1.default.createElement("div", { className: 'pt-10 pb-10' },
                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/files/fil024.svg', className: 'svg-icon-4x opacity-50' })),
                        react_1.default.createElement("div", { className: 'pb-15 fw-bold' },
                            react_1.default.createElement("h3", { className: 'text-gray-600 fs-5 mb-2' }, "No result found"),
                            react_1.default.createElement("div", { className: 'text-muted fs-7' }, "Please try again with a different query")))),
                react_1.default.createElement("form", { className: "pt-1 ".concat(menuState === 'advanced' ? '' : 'd-none') },
                    react_1.default.createElement("h3", { className: 'fw-bold text-dark mb-7' }, "Advanced Search"),
                    react_1.default.createElement("div", { className: 'mb-5' },
                        react_1.default.createElement("input", { type: 'text', className: 'form-control form-control-sm form-control-solid', placeholder: 'Contains the word', name: 'query' })),
                    react_1.default.createElement("div", { className: 'mb-5' },
                        react_1.default.createElement("div", { className: 'nav-group nav-group-fluid' },
                            react_1.default.createElement("label", null,
                                react_1.default.createElement("input", { type: 'radio', className: 'btn-check', name: 'type', value: 'has', defaultChecked: true }),
                                react_1.default.createElement("span", { className: 'btn btn-sm btn-color-muted btn-active btn-active-primary' }, "All")),
                            react_1.default.createElement("label", null,
                                react_1.default.createElement("input", { type: 'radio', className: 'btn-check', name: 'type', value: 'users' }),
                                react_1.default.createElement("span", { className: 'btn btn-sm btn-color-muted btn-active btn-active-primary px-4' }, "Users")),
                            react_1.default.createElement("label", null,
                                react_1.default.createElement("input", { type: 'radio', className: 'btn-check', name: 'type', value: 'orders' }),
                                react_1.default.createElement("span", { className: 'btn btn-sm btn-color-muted btn-active btn-active-primary px-4' }, "Orders")),
                            react_1.default.createElement("label", null,
                                react_1.default.createElement("input", { type: 'radio', className: 'btn-check', name: 'type', value: 'projects' }),
                                react_1.default.createElement("span", { className: 'btn btn-sm btn-color-muted btn-active btn-active-primary px-4' }, "Projects")))),
                    react_1.default.createElement("div", { className: 'mb-5' },
                        react_1.default.createElement("input", { type: 'text', name: 'assignedto', className: 'form-control form-control-sm form-control-solid', placeholder: 'Assigned to' })),
                    react_1.default.createElement("div", { className: 'mb-5' },
                        react_1.default.createElement("input", { type: 'text', name: 'collaborators', className: 'form-control form-control-sm form-control-solid', placeholder: 'Collaborators' })),
                    react_1.default.createElement("div", { className: 'mb-5' },
                        react_1.default.createElement("div", { className: 'nav-group nav-group-fluid' },
                            react_1.default.createElement("label", null,
                                react_1.default.createElement("input", { type: 'radio', className: 'btn-check', name: 'attachment', value: 'has', defaultChecked: true }),
                                react_1.default.createElement("span", { className: 'btn btn-sm btn-color-muted btn-active btn-active-primary' }, "Has attachment")),
                            react_1.default.createElement("label", null,
                                react_1.default.createElement("input", { type: 'radio', className: 'btn-check', name: 'attachment', value: 'any' }),
                                react_1.default.createElement("span", { className: 'btn btn-sm btn-color-muted btn-active btn-active-primary px-4' }, "Any")))),
                    react_1.default.createElement("div", { className: 'mb-5' },
                        react_1.default.createElement("select", { name: 'timezone', "aria-label": 'Select a Timezone', "data-control": 'select2', "data-placeholder": 'date_period', className: 'form-select form-select-sm form-select-solid' },
                            react_1.default.createElement("option", { value: 'next' }, "Within the next"),
                            react_1.default.createElement("option", { value: 'last' }, "Within the last"),
                            react_1.default.createElement("option", { value: 'between' }, "Between"),
                            react_1.default.createElement("option", { value: 'on' }, "On"))),
                    react_1.default.createElement("div", { className: 'row mb-8' },
                        react_1.default.createElement("div", { className: 'col-6' },
                            react_1.default.createElement("input", { type: 'number', name: 'date_number', className: 'form-control form-control-sm form-control-solid', placeholder: 'Lenght' })),
                        react_1.default.createElement("div", { className: 'col-6' },
                            react_1.default.createElement("select", { name: 'date_typer', "aria-label": 'Select a Timezone', "data-control": 'select2', "data-placeholder": 'Period', className: 'form-select form-select-sm form-select-solid' },
                                react_1.default.createElement("option", { value: 'days' }, "Days"),
                                react_1.default.createElement("option", { value: 'weeks' }, "Weeks"),
                                react_1.default.createElement("option", { value: 'months' }, "Months"),
                                react_1.default.createElement("option", { value: 'years' }, "Years")))),
                    react_1.default.createElement("div", { className: 'd-flex justify-content-end' },
                        react_1.default.createElement("button", { onClick: function (e) { e.preventDefault(); setMenuState("main"); }, className: 'btn btn-sm btn-light fw-bolder btn-active-light-primary me-2' }, "Cancel"),
                        react_1.default.createElement("a", { href: '/#', className: 'btn btn-sm fw-bolder btn-primary', "data-kt-search-element": 'advanced-options-form-search' }, "Search"))),
                react_1.default.createElement("form", { className: "pt-1 ".concat(menuState === 'preferences' ? '' : 'd-none') },
                    react_1.default.createElement("h3", { className: 'fw-bold text-dark mb-7' }, "Search Preferences"),
                    react_1.default.createElement("div", { className: 'pb-4 border-bottom' },
                        react_1.default.createElement("label", { className: 'form-check form-switch form-switch-sm form-check-custom form-check-solid flex-stack' },
                            react_1.default.createElement("span", { className: 'form-check-label text-gray-700 fs-6 fw-bold ms-0 me-2' }, "Projects"),
                            react_1.default.createElement("input", { className: 'form-check-input', type: 'checkbox', value: '1', defaultChecked: true }))),
                    react_1.default.createElement("div", { className: 'py-4 border-bottom' },
                        react_1.default.createElement("label", { className: 'form-check form-switch form-switch-sm form-check-custom form-check-solid flex-stack' },
                            react_1.default.createElement("span", { className: 'form-check-label text-gray-700 fs-6 fw-bold ms-0 me-2' }, "Targets"),
                            react_1.default.createElement("input", { className: 'form-check-input', type: 'checkbox', value: '1', defaultChecked: true }))),
                    react_1.default.createElement("div", { className: 'py-4 border-bottom' },
                        react_1.default.createElement("label", { className: 'form-check form-switch form-switch-sm form-check-custom form-check-solid flex-stack' },
                            react_1.default.createElement("span", { className: 'form-check-label text-gray-700 fs-6 fw-bold ms-0 me-2' }, "Affiliate Programs"),
                            react_1.default.createElement("input", { className: 'form-check-input', type: 'checkbox', value: '1' }))),
                    react_1.default.createElement("div", { className: 'py-4 border-bottom' },
                        react_1.default.createElement("label", { className: 'form-check form-switch form-switch-sm form-check-custom form-check-solid flex-stack' },
                            react_1.default.createElement("span", { className: 'form-check-label text-gray-700 fs-6 fw-bold ms-0 me-2' }, "Referrals"),
                            react_1.default.createElement("input", { className: 'form-check-input', type: 'checkbox', value: '1', defaultChecked: true }))),
                    react_1.default.createElement("div", { className: 'py-4 border-bottom' },
                        react_1.default.createElement("label", { className: 'form-check form-switch form-switch-sm form-check-custom form-check-solid flex-stack' },
                            react_1.default.createElement("span", { className: 'form-check-label text-gray-700 fs-6 fw-bold ms-0 me-2' }, "Users"),
                            react_1.default.createElement("input", { className: 'form-check-input', type: 'checkbox' }))),
                    react_1.default.createElement("div", { className: 'd-flex justify-content-end pt-7' },
                        react_1.default.createElement("button", { onClick: function (e) { e.preventDefault(); setMenuState("main"); }, className: 'btn btn-sm btn-light fw-bolder btn-active-light-primary me-2' }, "Cancel"),
                        react_1.default.createElement("button", { className: 'btn btn-sm fw-bolder btn-primary' }, "Save Changes")))))));
};
exports.Search = Search;
