"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListsWidget8 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var Dropdown1_1 = require("../../content/dropdown/Dropdown1");
var ListsWidget8 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: 'card card-xl-stretch mb-5 mb-xl-8' },
        react_1.default.createElement("div", { className: 'card-header align-items-center border-0 mt-4' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'fw-bolder text-dark' }, "Latest Products"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "Gifts and more")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("button", { type: 'button', className: 'btn btn-sm btn-icon btn-color-primary btn-active-light-primary', "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'bottom-end', "data-kt-menu-flip": 'top-end' },
                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen024.svg', className: 'svg-icon-2' })),
                react_1.default.createElement(Dropdown1_1.Dropdown1, null))),
        react_1.default.createElement("div", { className: 'card-body pt-3' },
            react_1.default.createElement("div", { className: 'd-flex align-items-sm-center mb-7' },
                react_1.default.createElement("div", { className: 'symbol symbol-60px symbol-2by3 me-4' },
                    react_1.default.createElement("div", { className: 'symbol-label', style: { backgroundImage: "url(".concat((0, helpers_1.toAbsoluteUrl)('/media/stock/600x400/img-17.jpg'), ")") } })),
                react_1.default.createElement("div", { className: 'd-flex flex-row-fluid align-items-center flex-wrap my-lg-0 me-2' },
                    react_1.default.createElement("div", { className: 'flex-grow-1 my-lg-0 my-2 me-2' },
                        react_1.default.createElement("a", { href: '#', className: 'text-gray-800 fw-bolder text-hover-primary fs-6' }, "Cup & Green"),
                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block pt-1' }, "Visually stunning")),
                    react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                        react_1.default.createElement("div", { className: 'me-6' },
                            react_1.default.createElement("i", { className: 'fa fa-star-half-alt me-1 text-warning fs-5' }),
                            react_1.default.createElement("span", { className: 'text-gray-800 fw-bolder' }, "4.2")),
                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light btn-sm border-0' },
                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2 svg-icon-primary' }))))),
            react_1.default.createElement("div", { className: 'd-flex align-items-sm-center mb-7' },
                react_1.default.createElement("div", { className: 'symbol symbol-60px symbol-2by3 me-4' },
                    react_1.default.createElement("div", { className: 'symbol-label', style: { backgroundImage: "url(".concat((0, helpers_1.toAbsoluteUrl)('/media/stock/600x400/img-10.jpg'), ")") } })),
                react_1.default.createElement("div", { className: 'd-flex flex-row-fluid align-items-center flex-wrap my-lg-0 me-2' },
                    react_1.default.createElement("div", { className: 'flex-grow-1 my-lg-0 my-2 me-2' },
                        react_1.default.createElement("a", { href: '#', className: 'text-gray-800 fw-bolder text-hover-primary fs-6' }, "Pink Patterns"),
                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block pt-1' }, "Feminine all around")),
                    react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                        react_1.default.createElement("div", { className: 'me-6' },
                            react_1.default.createElement("i", { className: 'fa fa-star-half-alt me-1 text-warning fs-5' }),
                            react_1.default.createElement("span", { className: 'text-gray-800 fw-bolder' }, "5.0")),
                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light btn-sm border-0' },
                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2 svg-icon-primary' }))))),
            react_1.default.createElement("div", { className: 'd-flex align-items-sm-center mb-7' },
                react_1.default.createElement("div", { className: 'symbol symbol-60px symbol-2by3 me-4' },
                    react_1.default.createElement("div", { className: 'symbol-label', style: { backgroundImage: "url(".concat((0, helpers_1.toAbsoluteUrl)('/media/stock/600x400/img-1.jpg'), ")") } })),
                react_1.default.createElement("div", { className: 'd-flex flex-row-fluid align-items-center flex-wrap my-lg-0 me-2' },
                    react_1.default.createElement("div", { className: 'flex-grow-1 my-lg-0 my-2 me-2' },
                        react_1.default.createElement("a", { href: '#', className: 'text-gray-800 fw-bolder text-hover-primary fs-6' }, "Abstract Art"),
                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block pt-1' }, "The will to capture readers")),
                    react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                        react_1.default.createElement("div", { className: 'me-6' },
                            react_1.default.createElement("i", { className: 'fa fa-star-half-alt me-1 text-warning fs-5' }),
                            react_1.default.createElement("span", { className: 'text-gray-800 fw-bolder' }, "5.7")),
                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light btn-sm border-0' },
                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2 svg-icon-primary' }))))),
            react_1.default.createElement("div", { className: 'd-flex align-items-sm-center' },
                react_1.default.createElement("div", { className: 'symbol symbol-60px symbol-2by3 me-4' },
                    react_1.default.createElement("div", { className: 'symbol-label', style: { backgroundImage: "url(".concat((0, helpers_1.toAbsoluteUrl)('/media/stock/600x400/img-9.jpg'), ")") } })),
                react_1.default.createElement("div", { className: 'd-flex flex-row-fluid align-items-center flex-wrap my-lg-0 me-2' },
                    react_1.default.createElement("div", { className: 'flex-grow-1 my-lg-0 my-2 me-2' },
                        react_1.default.createElement("a", { href: '#', className: 'text-gray-800 fw-bolder text-hover-primary fs-6' }, "Desserts platter"),
                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block pt-1' }, "Food trends & inspirations")),
                    react_1.default.createElement("div", { className: 'd-flex align-items-center' },
                        react_1.default.createElement("div", { className: 'me-6' },
                            react_1.default.createElement("i", { className: 'fa fa-star-half-alt me-1 text-warning fs-5' }),
                            react_1.default.createElement("span", { className: 'text-gray-800 fw-bolder' }, "3.7")),
                        react_1.default.createElement("a", { href: '#', className: 'btn btn-icon btn-light btn-sm border-0' },
                            react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-2 svg-icon-primary' }))))))));
};
exports.ListsWidget8 = ListsWidget8;
