"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListsWidget4 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var Dropdown1_1 = require("../../content/dropdown/Dropdown1");
var ListsWidget4 = function (_a) {
    var className = _a.className, _b = _a.items, items = _b === void 0 ? 6 : _b;
    return (react_1.default.createElement("div", { className: 'card card-xl-stretch mb-xl-8' },
        react_1.default.createElement("div", { className: 'card-header border-0 pt-5' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'card-label fw-bolder text-dark' }, "Trends"),
                react_1.default.createElement("span", { className: 'text-muted mt-1 fw-bold fs-7' }, "Latest tech trends")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("button", { type: 'button', className: 'btn btn-sm btn-icon btn-color-primary btn-active-light-primary', "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'bottom-end', "data-kt-menu-flip": 'top-end' },
                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen024.svg', className: 'svg-icon-2' })),
                react_1.default.createElement(Dropdown1_1.Dropdown1, null))),
        react_1.default.createElement("div", { className: 'card-body pt-5' },
            react_1.default.createElement("div", { className: 'd-flex align-items-sm-center mb-7' },
                react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                    react_1.default.createElement("span", { className: 'symbol-label' },
                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/plurk.svg'), className: 'h-50 align-self-center', alt: '' }))),
                react_1.default.createElement("div", { className: 'd-flex align-items-center flex-row-fluid flex-wrap' },
                    react_1.default.createElement("div", { className: 'flex-grow-1 me-2' },
                        react_1.default.createElement("a", { href: '#', className: 'text-gray-800 text-hover-primary fs-6 fw-bolder' }, "Top Authors"),
                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Mark, Rowling, Esther")),
                    react_1.default.createElement("span", { className: 'badge badge-light fw-bolder my-2' }, "+82$"))),
            react_1.default.createElement("div", { className: 'd-flex align-items-sm-center mb-7' },
                react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                    react_1.default.createElement("span", { className: 'symbol-label' },
                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/telegram.svg'), className: 'h-50 align-self-center', alt: '' }))),
                react_1.default.createElement("div", { className: 'd-flex align-items-center flex-row-fluid flex-wrap' },
                    react_1.default.createElement("div", { className: 'flex-grow-1 me-2' },
                        react_1.default.createElement("a", { href: '#', className: 'text-gray-800 text-hover-primary fs-6 fw-bolder' }, "Popular Authors"),
                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Randy, Steve, Mike")),
                    react_1.default.createElement("span", { className: 'badge badge-light fw-bolder my-2' }, "+280$"))),
            react_1.default.createElement("div", { className: 'd-flex align-items-sm-center mb-7' },
                react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                    react_1.default.createElement("span", { className: 'symbol-label' },
                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/vimeo.svg'), className: 'h-50 align-self-center', alt: '' }))),
                react_1.default.createElement("div", { className: 'd-flex align-items-center flex-row-fluid flex-wrap' },
                    react_1.default.createElement("div", { className: 'flex-grow-1 me-2' },
                        react_1.default.createElement("a", { href: '#', className: 'text-gray-800 text-hover-primary fs-6 fw-bolder' }, "New Users"),
                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "John, Pat, Jimmy")),
                    react_1.default.createElement("span", { className: 'badge badge-light fw-bolder my-2' }, "+4500$"))),
            react_1.default.createElement("div", { className: 'd-flex align-items-sm-center mb-7' },
                react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                    react_1.default.createElement("span", { className: 'symbol-label' },
                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/bebo.svg'), className: 'h-50 align-self-center', alt: '' }))),
                react_1.default.createElement("div", { className: 'd-flex align-items-center flex-row-fluid flex-wrap' },
                    react_1.default.createElement("div", { className: 'flex-grow-1 me-2' },
                        react_1.default.createElement("a", { href: '#', className: 'text-gray-800 text-hover-primary fs-6 fw-bolder' }, "Active Customers"),
                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Mark, Rowling, Esther")),
                    react_1.default.createElement("span", { className: 'badge badge-light fw-bolder my-2' }, "+4500$"))),
            items > 4 && (react_1.default.createElement("div", { className: 'd-flex align-items-sm-center mb-7' },
                react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                    react_1.default.createElement("span", { className: 'symbol-label' },
                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/kickstarter.svg'), className: 'h-50 align-self-center', alt: '' }))),
                react_1.default.createElement("div", { className: 'd-flex align-items-center flex-row-fluid flex-wrap' },
                    react_1.default.createElement("div", { className: 'flex-grow-1 me-2' },
                        react_1.default.createElement("a", { href: '#', className: 'text-gray-800 text-hover-primary fs-6 fw-bolder' }, "Bestseller Theme"),
                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Disco, Retro, Sports")),
                    react_1.default.createElement("span", { className: 'badge badge-light fw-bolder my-2' }, "+4500$")))),
            items > 5 && (react_1.default.createElement("div", { className: 'd-flex align-items-sm-center' },
                react_1.default.createElement("div", { className: 'symbol symbol-50px me-5' },
                    react_1.default.createElement("span", { className: 'symbol-label' },
                        react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/brand-logos/fox-hub.svg'), className: 'h-50 align-self-center', alt: '' }))),
                react_1.default.createElement("div", { className: 'd-flex align-items-center flex-row-fluid flex-wrap' },
                    react_1.default.createElement("div", { className: 'flex-grow-1 me-2' },
                        react_1.default.createElement("a", { href: '#', className: 'text-gray-800 text-hover-primary fs-6 fw-bolder' }, "Fox Broker App"),
                        react_1.default.createElement("span", { className: 'text-muted fw-bold d-block fs-7' }, "Finance, Corporate, Apps")),
                    react_1.default.createElement("span", { className: 'badge badge-light fw-bolder my-2' }, "+4500$")))))));
};
exports.ListsWidget4 = ListsWidget4;
