"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListsWidget5 = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var helpers_1 = require("../../../helpers");
var Dropdown1_1 = require("../../content/dropdown/Dropdown1");
var ListsWidget5 = function (_a) {
    var className = _a.className;
    return (react_1.default.createElement("div", { className: "card ".concat(className) },
        react_1.default.createElement("div", { className: 'card-header align-items-center border-0 mt-4' },
            react_1.default.createElement("h3", { className: 'card-title align-items-start flex-column' },
                react_1.default.createElement("span", { className: 'fw-bolder mb-2 text-dark' }, "Activities"),
                react_1.default.createElement("span", { className: 'text-muted fw-bold fs-7' }, "890 Records")),
            react_1.default.createElement("div", { className: 'card-toolbar' },
                react_1.default.createElement("button", { type: 'button', className: 'btn btn-sm btn-icon btn-color-primary btn-active-light-primary', "data-kt-menu-trigger": 'click', "data-kt-menu-placement": 'bottom-end', "data-kt-menu-flip": 'top-end' },
                    react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/general/gen024.svg', className: 'svg-icon-2' })),
                react_1.default.createElement(Dropdown1_1.Dropdown1, null))),
        react_1.default.createElement("div", { className: 'card-body pt-5' },
            react_1.default.createElement("div", { className: 'timeline-label' },
                react_1.default.createElement("div", { className: 'timeline-item' },
                    react_1.default.createElement("div", { className: 'timeline-label fw-bolder text-gray-800 fs-6' }, "08:42"),
                    react_1.default.createElement("div", { className: 'timeline-badge' },
                        react_1.default.createElement("i", { className: 'fa fa-genderless text-warning fs-1' })),
                    react_1.default.createElement("div", { className: 'fw-mormal timeline-content text-muted ps-3' }, "Outlines keep you honest. And keep structure")),
                react_1.default.createElement("div", { className: 'timeline-item' },
                    react_1.default.createElement("div", { className: 'timeline-label fw-bolder text-gray-800 fs-6' }, "10:00"),
                    react_1.default.createElement("div", { className: 'timeline-badge' },
                        react_1.default.createElement("i", { className: 'fa fa-genderless text-success fs-1' })),
                    react_1.default.createElement("div", { className: 'timeline-content d-flex' },
                        react_1.default.createElement("span", { className: 'fw-bolder text-gray-800 ps-3' }, "AEOL meeting"))),
                react_1.default.createElement("div", { className: 'timeline-item' },
                    react_1.default.createElement("div", { className: 'timeline-label fw-bolder text-gray-800 fs-6' }, "14:37"),
                    react_1.default.createElement("div", { className: 'timeline-badge' },
                        react_1.default.createElement("i", { className: 'fa fa-genderless text-danger fs-1' })),
                    react_1.default.createElement("div", { className: 'timeline-content fw-bolder text-gray-800 ps-3' },
                        "Make deposit",
                        react_1.default.createElement("a", { href: '#', className: 'text-primary' }, "USD 700"),
                        ". to ESL")),
                react_1.default.createElement("div", { className: 'timeline-item' },
                    react_1.default.createElement("div", { className: 'timeline-label fw-bolder text-gray-800 fs-6' }, "16:50"),
                    react_1.default.createElement("div", { className: 'timeline-badge' },
                        react_1.default.createElement("i", { className: 'fa fa-genderless text-primary fs-1' })),
                    react_1.default.createElement("div", { className: 'timeline-content fw-mormal text-muted ps-3' }, "Indulging in poorly driving and keep structure keep great")),
                react_1.default.createElement("div", { className: 'timeline-item' },
                    react_1.default.createElement("div", { className: 'timeline-label fw-bolder text-gray-800 fs-6' }, "21:03"),
                    react_1.default.createElement("div", { className: 'timeline-badge' },
                        react_1.default.createElement("i", { className: 'fa fa-genderless text-danger fs-1' })),
                    react_1.default.createElement("div", { className: 'timeline-content fw-bold text-gray-800 ps-3' },
                        "New order placed",
                        react_1.default.createElement("a", { href: '#', className: 'text-primary' }, "#XF-2356"),
                        ".")),
                react_1.default.createElement("div", { className: 'timeline-item' },
                    react_1.default.createElement("div", { className: 'timeline-label fw-bolder text-gray-800 fs-6' }, "16:50"),
                    react_1.default.createElement("div", { className: 'timeline-badge' },
                        react_1.default.createElement("i", { className: 'fa fa-genderless text-primary fs-1' })),
                    react_1.default.createElement("div", { className: 'timeline-content fw-mormal text-muted ps-3' }, "Indulging in poorly driving and keep structure keep great")),
                react_1.default.createElement("div", { className: 'timeline-item' },
                    react_1.default.createElement("div", { className: 'timeline-label fw-bolder text-gray-800 fs-6' }, "21:03"),
                    react_1.default.createElement("div", { className: 'timeline-badge' },
                        react_1.default.createElement("i", { className: 'fa fa-genderless text-danger fs-1' })),
                    react_1.default.createElement("div", { className: 'timeline-content fw-bold text-gray-800 ps-3' },
                        "New order placed",
                        react_1.default.createElement("a", { href: '#', className: 'text-primary' }, "#XF-2356"),
                        ".")),
                react_1.default.createElement("div", { className: 'timeline-item' },
                    react_1.default.createElement("div", { className: 'timeline-label fw-bolder text-gray-800 fs-6' }, "10:30"),
                    react_1.default.createElement("div", { className: 'timeline-badge' },
                        react_1.default.createElement("i", { className: 'fa fa-genderless text-success fs-1' })),
                    react_1.default.createElement("div", { className: 'timeline-content fw-mormal text-muted ps-3' }, "Finance KPI Mobile app launch preparion meeting"))))));
};
exports.ListsWidget5 = ListsWidget5;
