"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HeaderNotificationsMenu = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var clsx_1 = require("clsx");
var react_router_dom_1 = require("react-router-dom");
var helpers_1 = require("../../../helpers");
var HeaderNotificationsMenu = function () { return (React.createElement("div", { className: 'menu menu-sub menu-sub-dropdown menu-column w-350px w-lg-375px', "data-kt-menu": 'true' },
    React.createElement("div", { className: 'd-flex flex-column bgi-no-repeat rounded-top', style: { backgroundImage: "url('".concat((0, helpers_1.toAbsoluteUrl)('/media/misc/pattern-1.jpg'), "')") } },
        React.createElement("h3", { className: 'text-white fw-bold px-9 mt-10 mb-6' },
            "Notifications ",
            React.createElement("span", { className: 'fs-8 opacity-75 ps-3' }, "24 reports")),
        React.createElement("ul", { className: 'nav nav-line-tabs nav-line-tabs-2x nav-stretch fw-bold px-9' },
            React.createElement("li", { className: 'nav-item' },
                React.createElement("a", { className: 'nav-link text-white opacity-75 opacity-state-100 pb-4', "data-bs-toggle": 'tab', href: '#kt_topbar_notifications_1' }, "Alerts")),
            React.createElement("li", { className: 'nav-item' },
                React.createElement("a", { className: 'nav-link text-white opacity-75 opacity-state-100 pb-4 active', "data-bs-toggle": 'tab', href: '#kt_topbar_notifications_2' }, "Updates")),
            React.createElement("li", { className: 'nav-item' },
                React.createElement("a", { className: 'nav-link text-white opacity-75 opacity-state-100 pb-4', "data-bs-toggle": 'tab', href: '#kt_topbar_notifications_3' }, "Logs")))),
    React.createElement("div", { className: 'tab-content' },
        React.createElement("div", { className: 'tab-pane fade', id: 'kt_topbar_notifications_1', role: 'tabpanel' },
            React.createElement("div", { className: 'scroll-y mh-325px my-5 px-8' }, helpers_1.defaultAlerts.map(function (alert, index) { return (React.createElement("div", { key: "alert".concat(index), className: 'd-flex flex-stack py-4' },
                React.createElement("div", { className: 'd-flex align-items-center' },
                    React.createElement("div", { className: 'symbol symbol-35px me-4' },
                        React.createElement("span", { className: (0, clsx_1.default)('symbol-label', "bg-light-".concat(alert.state)) },
                            ' ',
                            React.createElement(helpers_1.KTSVG, { path: "/media/".concat(alert.icon), className: "svg-icon-2 svg-icon-".concat(alert.state) }))),
                    React.createElement("div", { className: 'mb-0 me-2' },
                        React.createElement("a", { href: '#', className: 'fs-6 text-gray-800 text-hover-primary fw-bolder' }, alert.title),
                        React.createElement("div", { className: 'text-gray-400 fs-7' }, alert.description))),
                React.createElement("span", { className: 'badge badge-light fs-8' }, alert.time))); })),
            React.createElement("div", { className: 'py-3 text-center border-top' },
                React.createElement(react_router_dom_1.Link, { to: '/crafted/pages/profile', className: 'btn btn-color-gray-600 btn-active-color-primary' },
                    "View All ",
                    React.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-5' })))),
        React.createElement("div", { className: 'tab-pane fade show active', id: 'kt_topbar_notifications_2', role: 'tabpanel' },
            React.createElement("div", { className: 'd-flex flex-column px-9' },
                React.createElement("div", { className: 'pt-10 pb-0' },
                    React.createElement("h3", { className: 'text-dark text-center fw-bolder' }, "Get Pro Access"),
                    React.createElement("div", { className: 'text-center text-gray-600 fw-bold pt-1' }, "Outlines keep you honest. They stoping you from amazing poorly about drive"),
                    React.createElement("div", { className: 'text-center mt-5 mb-9' },
                        React.createElement("a", { href: '#', className: 'btn btn-sm btn-primary px-6', "data-bs-toggle": 'modal', "data-bs-target": '#kt_modal_upgrade_plan' }, "Upgrade"))),
                React.createElement("div", { className: 'text-center px-4' },
                    React.createElement("img", { className: 'mw-100 mh-200px', alt: 'metronic', src: (0, helpers_1.toAbsoluteUrl)('/media/illustrations/sketchy-1/1.png') })))),
        React.createElement("div", { className: 'tab-pane fade', id: 'kt_topbar_notifications_3', role: 'tabpanel' },
            React.createElement("div", { className: 'scroll-y mh-325px my-5 px-8' }, helpers_1.defaultLogs.map(function (log, index) { return (React.createElement("div", { key: "log".concat(index), className: 'd-flex flex-stack py-4' },
                React.createElement("div", { className: 'd-flex align-items-center me-2' },
                    React.createElement("span", { className: (0, clsx_1.default)('w-70px badge', "badge-light-".concat(log.state), 'me-4') }, log.code),
                    React.createElement("a", { href: '#', className: 'text-gray-800 text-hover-primary fw-bold' }, log.message),
                    React.createElement("span", { className: 'badge badge-light fs-8' }, log.time)))); })),
            React.createElement("div", { className: 'py-3 text-center border-top' },
                React.createElement(react_router_dom_1.Link, { to: '/crafted/pages/profile', className: 'btn btn-color-gray-600 btn-active-color-primary' },
                    "View All ",
                    React.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/arrows/arr064.svg', className: 'svg-icon-5' }))))))); };
exports.HeaderNotificationsMenu = HeaderNotificationsMenu;
