"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MegaMenu = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var MegaMenu = function () { return (react_1.default.createElement("div", { className: 'row', "data-kt-menu-dismiss": 'true' },
    react_1.default.createElement("div", { className: 'col-lg-4 border-left-lg-1' },
        react_1.default.createElement("div", { className: 'menu-inline menu-column menu-active-bg' },
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))))),
    react_1.default.createElement("div", { className: 'col-lg-4 border-left-lg-1' },
        react_1.default.createElement("div", { className: 'menu-inline menu-column menu-active-bg' },
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))))),
    react_1.default.createElement("div", { className: 'col-lg-4 border-left-lg-1' },
        react_1.default.createElement("div", { className: 'menu-inline menu-column menu-active-bg' },
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))),
            react_1.default.createElement("div", { className: 'menu-item' },
                react_1.default.createElement("a", { href: '#', className: 'menu-link' },
                    react_1.default.createElement("span", { className: 'menu-bullet' },
                        react_1.default.createElement("span", { className: 'bullet bullet-dot' })),
                    react_1.default.createElement("span", { className: 'menu-title' }, "Example link"))))))); };
exports.MegaMenu = MegaMenu;
