"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Step2 = void 0;
var react_1 = require("react");
var helpers_1 = require("../../../../../_metronic/helpers");
var formik_1 = require("formik");
var Step2 = function () {
    return (react_1.default.createElement("div", { className: 'w-100' },
        react_1.default.createElement("div", { className: 'pb-10 pb-lg-15' },
            react_1.default.createElement("h2", { className: 'fw-bolder text-dark' }, "Account Info"),
            react_1.default.createElement("div", { className: 'text-gray-400 fw-bold fs-6' },
                "If you need more info, please check out",
                react_1.default.createElement("a", { href: '/dashboard', className: 'link-primary fw-bolder' },
                    ' ',
                    "Help Page"),
                ".")),
        react_1.default.createElement("div", { className: 'mb-10 fv-row' },
            react_1.default.createElement("label", { className: 'd-flex align-items-center form-label mb-3' },
                "Specify Team Size",
                react_1.default.createElement("i", { className: 'fas fa-exclamation-circle ms-2 fs-7', "data-bs-toggle": 'tooltip', title: 'Provide your team size to help us setup your billing' })),
            react_1.default.createElement("div", { className: 'row mb-2', "data-kt-buttons": 'true' },
                react_1.default.createElement("div", { className: 'col' },
                    react_1.default.createElement(formik_1.Field, { type: 'radio', className: 'btn-check', name: 'accountTeamSize', value: '1-1', id: 'kt_account_team_size_select_1' }),
                    react_1.default.createElement("label", { className: 'btn btn-outline btn-outline-dashed btn-outline-default w-100 p-4', htmlFor: 'kt_account_team_size_select_1' },
                        react_1.default.createElement("span", { className: 'fw-bolder fs-3' }, "1-1"))),
                react_1.default.createElement("div", { className: 'col' },
                    react_1.default.createElement(formik_1.Field, { type: 'radio', className: 'btn-check', name: 'accountTeamSize', value: '2-10', id: 'kt_account_team_size_select_2' }),
                    react_1.default.createElement("label", { className: 'btn btn-outline btn-outline-dashed btn-outline-default w-100 p-4', htmlFor: 'kt_account_team_size_select_2' },
                        react_1.default.createElement("span", { className: 'fw-bolder fs-3' }, "2-10"))),
                react_1.default.createElement("div", { className: 'col' },
                    react_1.default.createElement(formik_1.Field, { type: 'radio', className: 'btn-check', name: 'accountTeamSize', value: '10-50', id: 'kt_account_team_size_select_3' }),
                    react_1.default.createElement("label", { className: 'btn btn-outline btn-outline-dashed btn-outline-default w-100 p-4', htmlFor: 'kt_account_team_size_select_3' },
                        react_1.default.createElement("span", { className: 'fw-bolder fs-3' }, "10-50"))),
                react_1.default.createElement("div", { className: 'col' },
                    react_1.default.createElement(formik_1.Field, { type: 'radio', className: 'btn-check', name: 'accountTeamSize', value: '50+', id: 'kt_account_team_size_select_4' }),
                    react_1.default.createElement("label", { className: 'btn btn-outline btn-outline-dashed btn-outline-default w-100 p-4', htmlFor: 'kt_account_team_size_select_4' },
                        react_1.default.createElement("span", { className: 'fw-bolder fs-3' }, "50+")))),
            react_1.default.createElement("div", { className: 'form-text' }, "Customers will see this shortened version of your statement descriptor")),
        react_1.default.createElement("div", { className: 'mb-10 fv-row' },
            react_1.default.createElement("label", { className: 'form-label mb-3' }, "Team Account Name"),
            react_1.default.createElement(formik_1.Field, { type: 'text', className: 'form-control form-control-lg form-control-solid', name: 'accountName' }),
            react_1.default.createElement("div", { className: 'text-danger mt-2' },
                react_1.default.createElement(formik_1.ErrorMessage, { name: 'accountName' }))),
        react_1.default.createElement("div", { className: 'mb-0 fv-row' },
            react_1.default.createElement("label", { className: 'd-flex align-items-center form-label mb-5' },
                "Select Account Plan",
                react_1.default.createElement("i", { className: 'fas fa-exclamation-circle ms-2 fs-7', "data-bs-toggle": 'tooltip', title: 'Monthly billing will be based on your account plan' })),
            react_1.default.createElement("div", { className: 'mb-0' },
                react_1.default.createElement("label", { className: 'd-flex flex-stack mb-5 cursor-pointer' },
                    react_1.default.createElement("span", { className: 'd-flex align-items-center me-2' },
                        react_1.default.createElement("span", { className: 'symbol symbol-50px me-6' },
                            react_1.default.createElement("span", { className: 'symbol-label' },
                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/finance/fin001.svg', className: 'svg-icon-1 svg-icon-gray-600' }))),
                        react_1.default.createElement("span", { className: 'd-flex flex-column' },
                            react_1.default.createElement("span", { className: 'fw-bolder text-gray-800 text-hover-primary fs-5' }, "Company Account"),
                            react_1.default.createElement("span", { className: 'fs-6 fw-bold text-gray-400' }, "Use images to enhance your post flow"))),
                    react_1.default.createElement("span", { className: 'form-check form-check-custom form-check-solid' },
                        react_1.default.createElement(formik_1.Field, { className: 'form-check-input', type: 'radio', name: 'accountPlan', value: '1' }))),
                react_1.default.createElement("label", { className: 'd-flex flex-stack mb-5 cursor-pointer' },
                    react_1.default.createElement("span", { className: 'd-flex align-items-center me-2' },
                        react_1.default.createElement("span", { className: 'symbol symbol-50px me-6' },
                            react_1.default.createElement("span", { className: 'symbol-label' },
                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/graphs/gra006.svg', className: 'svg-icon-1 svg-icon-gray-600' }))),
                        react_1.default.createElement("span", { className: 'd-flex flex-column' },
                            react_1.default.createElement("span", { className: 'fw-bolder text-gray-800 text-hover-primary fs-5' }, "Developer Account"),
                            react_1.default.createElement("span", { className: 'fs-6 fw-bold text-gray-400' }, "Use images to your post time"))),
                    react_1.default.createElement("span", { className: 'form-check form-check-custom form-check-solid' },
                        react_1.default.createElement(formik_1.Field, { className: 'form-check-input', type: 'radio', name: 'accountPlan', value: '2' }))),
                react_1.default.createElement("label", { className: 'd-flex flex-stack mb-0 cursor-pointer' },
                    react_1.default.createElement("span", { className: 'd-flex align-items-center me-2' },
                        react_1.default.createElement("span", { className: 'symbol symbol-50px me-6' },
                            react_1.default.createElement("span", { className: 'symbol-label' },
                                react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/graphs/gra008.svg', className: 'svg-icon-1 svg-icon-gray-600' }))),
                        react_1.default.createElement("span", { className: 'd-flex flex-column' },
                            react_1.default.createElement("span", { className: 'fw-bolder text-gray-800 text-hover-primary fs-5' }, "Testing Account"),
                            react_1.default.createElement("span", { className: 'fs-6 fw-bold text-gray-400' }, "Use images to enhance time travel rivers"))),
                    react_1.default.createElement("span", { className: 'form-check form-check-custom form-check-solid' },
                        react_1.default.createElement(formik_1.Field, { className: 'form-check-input', type: 'radio', name: 'accountPlan', value: '3' })))))));
};
exports.Step2 = Step2;
