"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Step4 = void 0;
var react_1 = require("react");
var helpers_1 = require("../../../../../_metronic/helpers");
var formik_1 = require("formik");
var Step4 = function () {
    return (react_1.default.createElement("div", { className: 'w-100' },
        react_1.default.createElement("div", { className: 'pb-10 pb-lg-15' },
            react_1.default.createElement("h2", { className: 'fw-bolder text-dark' }, "Billing Details"),
            react_1.default.createElement("div", { className: 'text-gray-400 fw-bold fs-6' },
                "If you need more info, please check out",
                react_1.default.createElement("a", { href: '/dashboard', className: 'text-primary fw-bolder' },
                    ' ',
                    "Help Page"),
                ".")),
        react_1.default.createElement("div", { className: 'd-flex flex-column mb-7 fv-row' },
            react_1.default.createElement("label", { className: 'd-flex align-items-center fs-6 fw-bold form-label mb-2' },
                react_1.default.createElement("span", { className: 'required' }, "Name On Card"),
                react_1.default.createElement("i", { className: 'fas fa-exclamation-circle ms-2 fs-7', "data-bs-toggle": 'tooltip', title: "Specify a card holder's name" })),
            react_1.default.createElement(formik_1.Field, { type: 'text', className: 'form-control form-control-solid', placeholder: '', name: 'nameOnCard' }),
            react_1.default.createElement("div", { className: 'text-danger mt-2' },
                react_1.default.createElement(formik_1.ErrorMessage, { name: 'nameOnCard' }))),
        react_1.default.createElement("div", { className: 'd-flex flex-column mb-7 fv-row' },
            react_1.default.createElement("label", { className: 'required fs-6 fw-bold form-label mb-2' }, "Card Number"),
            react_1.default.createElement("div", { className: 'position-relative' },
                react_1.default.createElement(formik_1.Field, { type: 'text', className: 'form-control form-control-solid', placeholder: 'Enter card number', name: 'cardNumber' }),
                react_1.default.createElement("div", { className: 'text-danger mt-2' },
                    react_1.default.createElement(formik_1.ErrorMessage, { name: 'cardNumber' })),
                react_1.default.createElement("div", { className: 'position-absolute translate-middle-y top-50 end-0 me-5' },
                    react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/card-logos/visa.svg'), alt: '', className: 'h-25px' }),
                    react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/card-logos/mastercard.svg'), alt: '', className: 'h-25px' }),
                    react_1.default.createElement("img", { src: (0, helpers_1.toAbsoluteUrl)('/media/svg/card-logos/american-express.svg'), alt: '', className: 'h-25px' })))),
        react_1.default.createElement("div", { className: 'row mb-10' },
            react_1.default.createElement("div", { className: 'col-md-8 fv-row' },
                react_1.default.createElement("label", { className: 'required fs-6 fw-bold form-label mb-2' }, "Expiration Date"),
                react_1.default.createElement("div", { className: 'row fv-row' },
                    react_1.default.createElement("div", { className: 'col-6' },
                        react_1.default.createElement(formik_1.Field, { as: 'select', name: 'cardExpiryMonth', className: 'form-select form-select-solid' },
                            react_1.default.createElement("option", null),
                            react_1.default.createElement("option", { value: '1' }, "1"),
                            react_1.default.createElement("option", { value: '2' }, "2"),
                            react_1.default.createElement("option", { value: '3' }, "3"),
                            react_1.default.createElement("option", { value: '4' }, "4"),
                            react_1.default.createElement("option", { value: '5' }, "5"),
                            react_1.default.createElement("option", { value: '6' }, "6"),
                            react_1.default.createElement("option", { value: '7' }, "7"),
                            react_1.default.createElement("option", { value: '8' }, "8"),
                            react_1.default.createElement("option", { value: '9' }, "9"),
                            react_1.default.createElement("option", { value: '10' }, "10"),
                            react_1.default.createElement("option", { value: '11' }, "11"),
                            react_1.default.createElement("option", { value: '12' }, "12")),
                        react_1.default.createElement("div", { className: 'text-danger mt-2' },
                            react_1.default.createElement(formik_1.ErrorMessage, { name: 'cardExpiryMonth' }))),
                    react_1.default.createElement("div", { className: 'col-6' },
                        react_1.default.createElement(formik_1.Field, { as: 'select', name: 'cardExpiryYear', className: 'form-select form-select-solid' },
                            react_1.default.createElement("option", null),
                            react_1.default.createElement("option", { value: '2021' }, "2021"),
                            react_1.default.createElement("option", { value: '2022' }, "2022"),
                            react_1.default.createElement("option", { value: '2023' }, "2023"),
                            react_1.default.createElement("option", { value: '2024' }, "2024"),
                            react_1.default.createElement("option", { value: '2025' }, "2025"),
                            react_1.default.createElement("option", { value: '2026' }, "2026"),
                            react_1.default.createElement("option", { value: '2027' }, "2027"),
                            react_1.default.createElement("option", { value: '2028' }, "2028"),
                            react_1.default.createElement("option", { value: '2029' }, "2029"),
                            react_1.default.createElement("option", { value: '2030' }, "2030"),
                            react_1.default.createElement("option", { value: '2031' }, "2031")),
                        react_1.default.createElement("div", { className: 'text-danger mt-2' },
                            react_1.default.createElement(formik_1.ErrorMessage, { name: 'cardExpiryYear' }))))),
            react_1.default.createElement("div", { className: 'col-md-4 fv-row' },
                react_1.default.createElement("label", { className: 'd-flex align-items-center fs-6 fw-bold form-label mb-2' },
                    react_1.default.createElement("span", { className: 'required' }, "CVV"),
                    react_1.default.createElement("i", { className: 'fas fa-exclamation-circle ms-2 fs-7', "data-bs-toggle": 'tooltip', title: 'Enter a card CVV code' })),
                react_1.default.createElement("div", { className: 'position-relative' },
                    react_1.default.createElement(formik_1.Field, { type: 'text', className: 'form-control form-control-solid', minLength: 3, maxLength: 4, placeholder: 'CVV', name: 'cardCvv' }),
                    react_1.default.createElement("div", { className: 'text-danger mt-2' },
                        react_1.default.createElement(formik_1.ErrorMessage, { name: 'cardCvv' })),
                    react_1.default.createElement("div", { className: 'position-absolute translate-middle-y top-50 end-0 me-3' },
                        react_1.default.createElement(helpers_1.KTSVG, { path: '/media/icons/duotune/finance/fin002.svg', className: 'svg-icon-2hx' }))))),
        react_1.default.createElement("div", { className: 'd-flex flex-stack' },
            react_1.default.createElement("div", { className: 'me-5' },
                react_1.default.createElement("label", { className: 'fs-6 fw-bold form-label' }, "Save Card for further billing?"),
                react_1.default.createElement("div", { className: 'fs-7 fw-bold text-gray-400' }, "If you need more info, please check budget planning")),
            react_1.default.createElement("label", { className: 'form-check form-switch form-check-custom form-check-solid' },
                react_1.default.createElement(formik_1.Field, { className: 'form-check-input', type: 'checkbox', value: '1', checked: true }),
                react_1.default.createElement("span", { className: 'form-check-label fw-bold text-gray-400' }, "Save Card")))));
};
exports.Step4 = Step4;
