"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Overview = void 0;
/* eslint-disable jsx-a11y/anchor-is-valid */
var react_1 = require("react");
var react_router_dom_1 = require("react-router-dom");
var helpers_1 = require("../../../../_metronic/helpers");
var widgets_1 = require("../../../../_metronic/partials/widgets");
function Overview() {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement("div", { className: 'card mb-5 mb-xl-10', id: 'kt_profile_details_view' },
            react_1.default.createElement("div", { className: 'card-header cursor-pointer' },
                react_1.default.createElement("div", { className: 'card-title m-0' },
                    react_1.default.createElement("h3", { className: 'fw-bolder m-0' }, "Profile Details")),
                react_1.default.createElement(react_router_dom_1.Link, { to: '/crafted/account/settings', className: 'btn btn-primary align-self-center' }, "Edit Profile")),
            react_1.default.createElement("div", { className: 'card-body p-9' },
                react_1.default.createElement("div", { className: 'row mb-7' },
                    react_1.default.createElement("label", { className: 'col-lg-4 fw-bold text-muted' }, "Full Name"),
                    react_1.default.createElement("div", { className: 'col-lg-8' },
                        react_1.default.createElement("span", { className: 'fw-bolder fs-6 text-dark' }, "Max Smith"))),
                react_1.default.createElement("div", { className: 'row mb-7' },
                    react_1.default.createElement("label", { className: 'col-lg-4 fw-bold text-muted' }, "Company"),
                    react_1.default.createElement("div", { className: 'col-lg-8 fv-row' },
                        react_1.default.createElement("span", { className: 'fw-bold fs-6' }, "Keenthemes"))),
                react_1.default.createElement("div", { className: 'row mb-7' },
                    react_1.default.createElement("label", { className: 'col-lg-4 fw-bold text-muted' },
                        "Contact Phone",
                        react_1.default.createElement("i", { className: 'fas fa-exclamation-circle ms-1 fs-7', "data-bs-toggle": 'tooltip', title: 'Phone number must be active' })),
                    react_1.default.createElement("div", { className: 'col-lg-8 d-flex align-items-center' },
                        react_1.default.createElement("span", { className: 'fw-bolder fs-6 me-2' }, "044 3276 454 935"),
                        react_1.default.createElement("span", { className: 'badge badge-success' }, "Verified"))),
                react_1.default.createElement("div", { className: 'row mb-7' },
                    react_1.default.createElement("label", { className: 'col-lg-4 fw-bold text-muted' }, "Company Site"),
                    react_1.default.createElement("div", { className: 'col-lg-8' },
                        react_1.default.createElement("a", { href: '#', className: 'fw-bold fs-6 text-dark text-hover-primary' }, "keenthemes.com"))),
                react_1.default.createElement("div", { className: 'row mb-7' },
                    react_1.default.createElement("label", { className: 'col-lg-4 fw-bold text-muted' },
                        "Country",
                        react_1.default.createElement("i", { className: 'fas fa-exclamation-circle ms-1 fs-7', "data-bs-toggle": 'tooltip', title: 'Country of origination' })),
                    react_1.default.createElement("div", { className: 'col-lg-8' },
                        react_1.default.createElement("span", { className: 'fw-bolder fs-6 text-dark' }, "Germany"))),
                react_1.default.createElement("div", { className: 'row mb-7' },
                    react_1.default.createElement("label", { className: 'col-lg-4 fw-bold text-muted' }, "Communication"),
                    react_1.default.createElement("div", { className: 'col-lg-8' },
                        react_1.default.createElement("span", { className: 'fw-bolder fs-6 text-dark' }, "Email, Phone"))),
                react_1.default.createElement("div", { className: 'row mb-10' },
                    react_1.default.createElement("label", { className: 'col-lg-4 fw-bold text-muted' }, "Allow Changes"),
                    react_1.default.createElement("div", { className: 'col-lg-8' },
                        react_1.default.createElement("span", { className: 'fw-bold fs-6' }, "Yes"))),
                react_1.default.createElement("div", { className: 'notice d-flex bg-light-warning rounded border-warning border border-dashed p-6' },
                    react_1.default.createElement(helpers_1.KTSVG, { path: 'icons/duotune/general/gen044.svg', className: 'svg-icon-2tx svg-icon-warning me-4' }),
                    react_1.default.createElement("div", { className: 'd-flex flex-stack flex-grow-1' },
                        react_1.default.createElement("div", { className: 'fw-bold' },
                            react_1.default.createElement("h4", { className: 'text-gray-800 fw-bolder' }, "We need your attention!"),
                            react_1.default.createElement("div", { className: 'fs-6 text-gray-600' },
                                "Your payment was declined. To start using tools, please",
                                react_1.default.createElement(react_router_dom_1.Link, { className: 'fw-bolder', to: '/crafted/account/settings' },
                                    ' ',
                                    "Add Payment Method"),
                                ".")))))),
        react_1.default.createElement("div", { className: 'row gy-10 gx-xl-10' },
            react_1.default.createElement("div", { className: 'col-xl-6' },
                react_1.default.createElement(widgets_1.ChartsWidget1, { className: 'card-xxl-stretch mb-5 mb-xl-10' })),
            react_1.default.createElement("div", { className: 'col-xl-6' },
                react_1.default.createElement(widgets_1.TablesWidget1, { className: 'card-xxl-stretch mb-5 mb-xl-10' }))),
        react_1.default.createElement("div", { className: 'row gy-10 gx-xl-10' },
            react_1.default.createElement("div", { className: 'col-xl-6' },
                react_1.default.createElement(widgets_1.ListsWidget5, { className: 'card-xxl-stretch mb-5 mb-xl-10' })),
            react_1.default.createElement("div", { className: 'col-xl-6' },
                react_1.default.createElement(widgets_1.TablesWidget5, { className: 'card-xxl-stretch mb-5 mb-xl-10' })))));
}
exports.Overview = Overview;
